type SeedRow = Record<string, unknown>;

export type ContourSeedBlueprint = {
  users: SeedRow[];
  listings: SeedRow[];
  clients: SeedRow[];
  deals: SeedRow[];
  workItems: SeedRow[];
  listingUtilities: SeedRow[];
  clientPreferredLocations: SeedRow[];
  dealListings: SeedRow[];
  interactions: SeedRow[];
  paymentPlans: SeedRow[];
  installmentScheduleItems: SeedRow[];
  rentalLeases: SeedRow[];
  rentalCharges: SeedRow[];
  payments: SeedRow[];
  documents: SeedRow[];
  insights: SeedRow[];
  syncDevices: SeedRow[];
  syncState: SeedRow[];
  events: SeedRow[];
  auditLogs: SeedRow[];
};

type CaseTemplate = {
  key: string;
  listingTitle: string;
  area: string;
  address: string;
  latitude: number;
  longitude: number;
  ownerName: string;
  clientName: string;
  clientEmail: string;
  clientPhone: string;
  clientSource: string;
  clientSegment: string;
  clientNrc: string;
  clientPassport: string;
  clientTpin: string;
  nationality: string;
  budgetMinAmount: string;
  budgetMaxAmount: string;
  budgetCurrency: "ZMW" | "USD";
  clientNotes: string;
  preferredLocation: string;
  propertyType: string;
  listingStatus: "available" | "reserved" | "sold" | "under_maintenance";
  availabilityStatus: "available" | "reserved" | "under_maintenance" | "rented" | "sold";
  priceCents: number;
  currency: "ZMW" | "USD";
  listingCode: string;
  listingType: "property" | "vacant_land";
  askingPriceAmount: string;
  bedrooms: number | null;
  bathrooms: number | null;
  landSizeHa: string;
  zoning: "residential" | "commercial" | "agricultural" | "mixed" | "other";
  landDesignation: "state_land" | "customary_land";
  listingNotes: string;
  dealStage: "new_enquiry" | "qualified" | "site_visit" | "offer_made" | "negotiating" | "document_check" | "closing" | "won" | "lost";
  dealStatus: "open" | "won" | "lost";
  dealType: "sale" | "rental" | "installment";
  dealValueCents: number;
  dealOfferAmount: string;
  dealCommissionPercent: string;
  dealCommissionAmount: string;
  dealNotes: string;
  workItemStatus: "open" | "in_progress" | "blocked" | "done";
  workItemTone: "info" | "warning" | "danger" | "success";
  workItemKind: string;
  workItemDescription: string;
  workItemPriority: "low" | "medium" | "high";
  interactionType: "call" | "site_visit" | "whatsapp" | "email" | "negotiation" | "other";
  interactionOutcome: string;
  interactionSummary: string;
  interactionNextStep: string;
  planFrequency: "monthly" | "quarterly" | "custom";
  planPeriods: number;
  planStatus: "active" | "completed" | "cancelled";
  paymentPlanPrincipal: string;
  paymentPlanDownPayment: string;
  installmentStatus: "due" | "paid" | "overdue";
  installmentAmountDue: string;
  installmentAmountPaid: string;
  leaseStatus: "active" | "ended";
  leaseStage:
    | "enquiry_received"
    | "viewing_scheduled"
    | "viewing_completed"
    | "application_received"
    | "screening"
    | "lease_draft"
    | "active_tenancy"
    | "closed";
  leaseRentAmount: string;
  leaseBillingDay: number;
  leaseDepositAmount: string;
  chargeStatus: "due" | "paid" | "overdue";
  chargeAmount: string;
  paymentMethod: string;
  paymentAmount: string;
  paymentNotes: string;
  documentCategory: "title_deed" | "offer_letter" | "survey_diagram" | "site_plan" | "contract_of_sale" | "lease_agreement" | "other";
  documentName: string;
  documentNotes: string;
  documentVerified: boolean;
  insightSeverity: "info" | "warn" | "critical";
  insightStatus: "open" | "acknowledged" | "resolved" | "dismissed";
  insightType: string;
  insightTitle: string;
  insightDescription: string;
  insightRecommendedAction: string;
  insightEvidence: string;
  syncDeviceType: string;
  appVersion: string;
  syncErrorCode: string;
  auditAction: "insert" | "update" | "delete";
};

const seededAt = new Date("2026-06-13T09:00:00.000Z");

function iso(offsetDays: number, hour = 9) {
  const date = new Date(seededAt);
  date.setUTCDate(date.getUTCDate() + offsetDays);
  date.setUTCHours(hour, 0, 0, 0);
  return date.toISOString();
}

function money(value: number) {
  return value.toFixed(2);
}

const userRows: SeedRow[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    clerk_user_id: "demo-admin-primary",
    email: "admin.primary@contour.local",
    full_name: "Alicia Mwanza",
    role: "admin",
    is_active: true,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    clerk_user_id: "demo-agent-north",
    email: "agent.north@contour.local",
    full_name: "Brian Phiri",
    role: "agent",
    is_active: true,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    clerk_user_id: "demo-agent-south",
    email: "agent.south@contour.local",
    full_name: "Chipo Banda",
    role: "agent",
    is_active: true,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    clerk_user_id: "demo-finance",
    email: "finance@contour.local",
    full_name: "David Tembo",
    role: "finance",
    is_active: true,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    clerk_user_id: "demo-legal",
    email: "legal@contour.local",
    full_name: "Esther Chileshe",
    role: "legal",
    is_active: true,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "66666666-6666-4666-8666-666666666666",
    clerk_user_id: "demo-auditor",
    email: "auditor@contour.local",
    full_name: "Felix Mwale",
    role: "auditor",
    is_active: true,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "77777777-7777-4777-8777-777777777777",
    clerk_user_id: "demo-ops-admin",
    email: "ops.admin@contour.local",
    full_name: "Grace Soko",
    role: "admin",
    is_active: true,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "88888888-8888-4888-8888-888888888888",
    clerk_user_id: "demo-agent-west",
    email: "agent.west@contour.local",
    full_name: "Henry Kunda",
    role: "agent",
    is_active: true,
    created_at: seededAt,
    updated_at: seededAt,
  },
];

const cases: CaseTemplate[] = [
  {
    key: "lusaka-west-14",
    listingTitle: "Lusaka West 14",
    area: "Lusaka West",
    address: "14 Lusaka West Road, Lusaka",
    latitude: -15.4319437,
    longitude: 28.2034006,
    ownerName: "Moses Chanda",
    clientName: "Moses Chanda Family Trust",
    clientEmail: "m.chanda@example.com",
    clientPhone: "+260970000001",
    clientSource: "Referral",
    clientSegment: "active_tenant",
    clientNrc: "123456/11/1",
    clientPassport: "ZMBP-001",
    clientTpin: "TPIN-0001",
    nationality: "Zambian",
    budgetMinAmount: "1200000.00",
    budgetMaxAmount: "2200000.00",
    budgetCurrency: "ZMW",
    clientNotes: "Prefers west-facing family homes and a quick turn-around.",
    preferredLocation: "Lusaka West",
    propertyType: "Property",
    listingStatus: "available",
    availabilityStatus: "available",
    priceCents: 180000000,
    currency: "ZMW",
    listingCode: "LST-0001",
    listingType: "property",
    askingPriceAmount: "1800000.00",
    bedrooms: 4,
    bathrooms: 3,
    landSizeHa: "0.4800",
    zoning: "residential",
    landDesignation: "state_land",
    listingNotes: "Family home with a paved driveway and mature garden.",
    dealStage: "negotiating",
    dealStatus: "open",
    dealType: "sale",
    dealValueCents: 180000000,
    dealOfferAmount: "1800000.00",
    dealCommissionPercent: "3.50",
    dealCommissionAmount: "63000.00",
    dealNotes: "Strong buyer intent and clean title.",
    workItemStatus: "open",
    workItemTone: "warning",
    workItemKind: "Document request",
    workItemDescription: "Collect and verify the title deed before contract finalization.",
    workItemPriority: "high",
    interactionType: "call",
    interactionOutcome: "Viewing confirmed",
    interactionSummary: "Buyer confirmed a second viewing and requested a revised offer sheet.",
    interactionNextStep: "Send a revised offer sheet and confirm viewing feedback.",
    planFrequency: "monthly",
    planPeriods: 12,
    planStatus: "active",
    paymentPlanPrincipal: "1800000.00",
    paymentPlanDownPayment: "240000.00",
    installmentStatus: "paid",
    installmentAmountDue: "150000.00",
    installmentAmountPaid: "150000.00",
    leaseStatus: "active",
    leaseStage: "enquiry_received",
    leaseRentAmount: "9000.00",
    leaseBillingDay: 1,
    leaseDepositAmount: "2000.00",
    chargeStatus: "paid",
    chargeAmount: "9000.00",
    paymentMethod: "bank transfer",
    paymentAmount: "150000.00",
    paymentNotes: "Monthly installment and deposit reconciliation.",
    documentCategory: "title_deed",
    documentName: "Lusaka West 14 Title Deed",
    documentNotes: "Verified against the land registry and attached to the deal.",
    documentVerified: true,
    insightSeverity: "warn",
    insightStatus: "open",
    insightType: "stale_listing",
    insightTitle: "Review stale listing",
    insightDescription: "The home needs refreshed photos and a status check.",
    insightRecommendedAction: "Contact the owner and refresh the gallery.",
    insightEvidence: "14 days since last meaningful update.",
    syncDeviceType: "electron_desktop",
    appVersion: "0.9.0",
    syncErrorCode: "sync_ok",
    auditAction: "insert",
  },
  {
    key: "woodlands-09",
    listingTitle: "Woodlands 09",
    area: "Woodlands",
    address: "9 Woodlands Avenue, Lusaka",
    latitude: -15.4369066,
    longitude: 28.3411414,
    ownerName: "Nalia Banda",
    clientName: "Nalia Banda",
    clientEmail: "n.banda@example.com",
    clientPhone: "+260970000002",
    clientSource: "Website",
    clientSegment: "prospective_buyer",
    clientNrc: "223456/11/1",
    clientPassport: "ZMBP-002",
    clientTpin: "TPIN-0002",
    nationality: "Zambian",
    budgetMinAmount: "1500000.00",
    budgetMaxAmount: "2500000.00",
    budgetCurrency: "USD",
    clientNotes: "Shortlist focused on Woodlands and Kabulonga.",
    preferredLocation: "Woodlands",
    propertyType: "Property",
    listingStatus: "reserved",
    availabilityStatus: "reserved",
    priceCents: 18500000,
    currency: "USD",
    listingCode: "LST-0002",
    listingType: "property",
    askingPriceAmount: "185000.00",
    bedrooms: 3,
    bathrooms: 2,
    landSizeHa: "0.2200",
    zoning: "commercial",
    landDesignation: "customary_land",
    listingNotes: "Reserved pending contract and verification pack.",
    dealStage: "closing",
    dealStatus: "open",
    dealType: "sale",
    dealValueCents: 18500000,
    dealOfferAmount: "185000.00",
    dealCommissionPercent: "2.50",
    dealCommissionAmount: "4625.00",
    dealNotes: "Awaiting final signatures and payment instructions.",
    workItemStatus: "in_progress",
    workItemTone: "info",
    workItemKind: "Follow-up",
    workItemDescription: "Call the buyer and confirm the contract review slot.",
    workItemPriority: "medium",
    interactionType: "site_visit",
    interactionOutcome: "Offer requested",
    interactionSummary: "Buyer visited with architect and requested a revised plan.",
    interactionNextStep: "Send contract pack and revised payment schedule.",
    planFrequency: "monthly",
    planPeriods: 10,
    planStatus: "active",
    paymentPlanPrincipal: "185000.00",
    paymentPlanDownPayment: "35000.00",
    installmentStatus: "due",
    installmentAmountDue: "18500.00",
    installmentAmountPaid: "0.00",
    leaseStatus: "ended",
    leaseStage: "viewing_scheduled",
    leaseRentAmount: "9500.00",
    leaseBillingDay: 5,
    leaseDepositAmount: "2500.00",
    chargeStatus: "due",
    chargeAmount: "9500.00",
    paymentMethod: "cash",
    paymentAmount: "18500.00",
    paymentNotes: "Deposit reserved for contract completion.",
    documentCategory: "offer_letter",
    documentName: "Woodlands 09 Offer Letter",
    documentNotes: "Pending buyer signature and witness confirmation.",
    documentVerified: false,
    insightSeverity: "critical",
    insightStatus: "open",
    insightType: "follow_up_gap",
    insightTitle: "Client follow-up gap",
    insightDescription: "The buyer has not been contacted in seven days.",
    insightRecommendedAction: "Send a WhatsApp follow-up and confirm timing.",
    insightEvidence: "7 days since last interaction.",
    syncDeviceType: "electron_desktop",
    appVersion: "0.9.0",
    syncErrorCode: "retry_pending",
    auditAction: "insert",
  },
  {
    key: "ndola-north-24",
    listingTitle: "Ndola North 24",
    area: "Ndola North",
    address: "24 Ndola North Drive, Ndola",
    latitude: -12.9693056,
    longitude: 28.6365894,
    ownerName: "Estate Trust Zambia",
    clientName: "Estate Trust Zambia",
    clientEmail: "trust@example.com",
    clientPhone: "+260970000003",
    clientSource: "Legacy import",
    clientSegment: "land_owner_seller",
    clientNrc: "323456/11/1",
    clientPassport: "ZMBP-003",
    clientTpin: "TPIN-0003",
    nationality: "Zambian",
    budgetMinAmount: "400000.00",
    budgetMaxAmount: "800000.00",
    budgetCurrency: "ZMW",
    clientNotes: "Long-term seller relationship with a clean title trail.",
    preferredLocation: "Ndola North",
    propertyType: "Vacant land",
    listingStatus: "under_maintenance",
    availabilityStatus: "under_maintenance",
    priceCents: 46000000,
    currency: "ZMW",
    listingCode: "LST-0003",
    listingType: "vacant_land",
    askingPriceAmount: "460000.00",
    bedrooms: null,
    bathrooms: null,
    landSizeHa: "0.4800",
    zoning: "agricultural",
    landDesignation: "customary_land",
    listingNotes: "Awaiting site cleanup and boundary confirmation.",
    dealStage: "site_visit",
    dealStatus: "won",
    dealType: "installment",
    dealValueCents: 46000000,
    dealOfferAmount: "460000.00",
    dealCommissionPercent: "4.00",
    dealCommissionAmount: "18400.00",
    dealNotes: "Completed transfer with documented handover.",
    workItemStatus: "blocked",
    workItemTone: "danger",
    workItemKind: "Audit check",
    workItemDescription: "Check for duplicate contact records before the next outreach.",
    workItemPriority: "high",
    interactionType: "whatsapp",
    interactionOutcome: "Docs requested",
    interactionSummary: "Seller shared updated site photos and requested transfer docs.",
    interactionNextStep: "Upload the survey diagram and transfer checklist.",
    planFrequency: "quarterly",
    planPeriods: 8,
    planStatus: "completed",
    paymentPlanPrincipal: "460000.00",
    paymentPlanDownPayment: "92000.00",
    installmentStatus: "paid",
    installmentAmountDue: "57500.00",
    installmentAmountPaid: "57500.00",
    leaseStatus: "active",
    leaseStage: "viewing_completed",
    leaseRentAmount: "3500.00",
    leaseBillingDay: 7,
    leaseDepositAmount: "1000.00",
    chargeStatus: "paid",
    chargeAmount: "3500.00",
    paymentMethod: "mobile money",
    paymentAmount: "57500.00",
    paymentNotes: "Installment cleared after transfer inspection.",
    documentCategory: "survey_diagram",
    documentName: "Ndola North 24 Survey Diagram",
    documentNotes: "Site diagram archived and cross-checked.",
    documentVerified: true,
    insightSeverity: "warn",
    insightStatus: "acknowledged",
    insightType: "missing_document",
    insightTitle: "Missing title deed attachment",
    insightDescription: "Deal is at contract stage but the deed is not attached.",
    insightRecommendedAction: "Upload the deed to the document vault.",
    insightEvidence: "Contract packet missing one critical attachment.",
    syncDeviceType: "tablet",
    appVersion: "1.0.0",
    syncErrorCode: "sync_ok",
    auditAction: "update",
  },
  {
    key: "livingstone-plot-88",
    listingTitle: "Livingstone Plot 88",
    area: "Livingstone Central",
    address: "Plot 88, Livingstone",
    latitude: -17.853135,
    longitude: 25.861429,
    ownerName: "Tawanda Phiri",
    clientName: "Tawanda Phiri",
    clientEmail: "t.phiri@example.com",
    clientPhone: "+260970000004",
    clientSource: "Walk-in",
    clientSegment: "past_lead",
    clientNrc: "423456/11/1",
    clientPassport: "ZMBP-004",
    clientTpin: "TPIN-0004",
    nationality: "Zambian",
    budgetMinAmount: "40000.00",
    budgetMaxAmount: "100000.00",
    budgetCurrency: "USD",
    clientNotes: "Interested in plot flips and compact rental stock.",
    preferredLocation: "Livingstone",
    propertyType: "Vacant land",
    listingStatus: "sold",
    availabilityStatus: "sold",
    priceCents: 5200000,
    currency: "USD",
    listingCode: "LST-0004",
    listingType: "vacant_land",
    askingPriceAmount: "52000.00",
    bedrooms: null,
    bathrooms: null,
    landSizeHa: "0.1200",
    zoning: "mixed",
    landDesignation: "state_land",
    listingNotes: "Closed sale with a clean boundary report.",
    dealStage: "won",
    dealStatus: "won",
    dealType: "sale",
    dealValueCents: 5200000,
    dealOfferAmount: "52000.00",
    dealCommissionPercent: "2.00",
    dealCommissionAmount: "1040.00",
    dealNotes: "Closed sale after final survey sign-off.",
    workItemStatus: "done",
    workItemTone: "success",
    workItemKind: "Closing",
    workItemDescription: "Prepare the closing pack and archive the deal.",
    workItemPriority: "medium",
    interactionType: "negotiation",
    interactionOutcome: "Closed won",
    interactionSummary: "Buyer accepted the final terms after survey review.",
    interactionNextStep: "Archive the record and schedule handover.",
    planFrequency: "monthly",
    planPeriods: 6,
    planStatus: "completed",
    paymentPlanPrincipal: "52000.00",
    paymentPlanDownPayment: "12000.00",
    installmentStatus: "paid",
    installmentAmountDue: "8666.67",
    installmentAmountPaid: "8666.67",
    leaseStatus: "ended",
    leaseStage: "application_received",
    leaseRentAmount: "4200.00",
    leaseBillingDay: 10,
    leaseDepositAmount: "1500.00",
    chargeStatus: "paid",
    chargeAmount: "4200.00",
    paymentMethod: "bank transfer",
    paymentAmount: "8666.67",
    paymentNotes: "Final installment and handover settlement.",
    documentCategory: "contract_of_sale",
    documentName: "Livingstone Plot 88 Sale Contract",
    documentNotes: "Signed contract and completion pack.",
    documentVerified: true,
    insightSeverity: "info",
    insightStatus: "resolved",
    insightType: "closing_ready",
    insightTitle: "Closing packet ready",
    insightDescription: "All required documents are present and verified.",
    insightRecommendedAction: "Close the loop and notify stakeholders.",
    insightEvidence: "No outstanding document gaps.",
    syncDeviceType: "electron_desktop",
    appVersion: "1.0.0",
    syncErrorCode: "sync_ok",
    auditAction: "insert",
  },
  {
    key: "chalala-ridge-07",
    listingTitle: "Chalala Ridge 07",
    area: "Chalala Ridge",
    address: "7 Chalala Ridge Avenue, Lusaka",
    latitude: -15.4728969,
    longitude: 28.3566099,
    ownerName: "Grace Chileshe",
    clientName: "Grace Chileshe",
    clientEmail: "g.chileshe@example.com",
    clientPhone: "+260970000005",
    clientSource: "Website",
    clientSegment: "active_tenant",
    clientNrc: "523456/11/1",
    clientPassport: "ZMBP-005",
    clientTpin: "TPIN-0005",
    nationality: "Zambian",
    budgetMinAmount: "8000.00",
    budgetMaxAmount: "14000.00",
    budgetCurrency: "USD",
    clientNotes: "Needs a quiet location with fast internet.",
    preferredLocation: "Chalala Ridge",
    propertyType: "Property",
    listingStatus: "available",
    availabilityStatus: "rented",
    priceCents: 9800000,
    currency: "USD",
    listingCode: "LST-0005",
    listingType: "property",
    askingPriceAmount: "98000.00",
    bedrooms: 2,
    bathrooms: 2,
    landSizeHa: "0.1800",
    zoning: "residential",
    landDesignation: "state_land",
    listingNotes: "Turn-key rental with solar backup and fibre.",
    dealStage: "new_enquiry",
    dealStatus: "open",
    dealType: "rental",
    dealValueCents: 9800000,
    dealOfferAmount: "98000.00",
    dealCommissionPercent: "2.75",
    dealCommissionAmount: "2695.00",
    dealNotes: "Tenant ready to move in after inspection.",
    workItemStatus: "open",
    workItemTone: "info",
    workItemKind: "Move-in",
    workItemDescription: "Confirm key handover and utilities activation.",
    workItemPriority: "medium",
    interactionType: "site_visit",
    interactionOutcome: "Move-in approved",
    interactionSummary: "Tenant toured the property and confirmed the layout.",
    interactionNextStep: "Send move-in checklist and lease draft.",
    planFrequency: "monthly",
    planPeriods: 12,
    planStatus: "active",
    paymentPlanPrincipal: "98000.00",
    paymentPlanDownPayment: "19600.00",
    installmentStatus: "due",
    installmentAmountDue: "8166.67",
    installmentAmountPaid: "0.00",
    leaseStatus: "active",
    leaseStage: "screening",
    leaseRentAmount: "9800.00",
    leaseBillingDay: 1,
    leaseDepositAmount: "2400.00",
    chargeStatus: "due",
    chargeAmount: "9800.00",
    paymentMethod: "cash",
    paymentAmount: "19600.00",
    paymentNotes: "Rental deposit and first month's rent.",
    documentCategory: "lease_agreement",
    documentName: "Chalala Ridge 07 Lease Agreement",
    documentNotes: "Tenant signed lease and property checklist attached.",
    documentVerified: false,
    insightSeverity: "warn",
    insightStatus: "open",
    insightType: "move_in_gap",
    insightTitle: "Move-in checklist pending",
    insightDescription: "Lease is ready but the property pack still needs review.",
    insightRecommendedAction: "Send the move-in checklist and verify utilities.",
    insightEvidence: "Two outstanding checklist items remain.",
    syncDeviceType: "web_app",
    appVersion: "1.0.1",
    syncErrorCode: "sync_ok",
    auditAction: "insert",
  },
  {
    key: "kabulonga-gardens-12",
    listingTitle: "Kabulonga Gardens 12",
    area: "Kabulonga",
    address: "12 Kabulonga Gardens, Lusaka",
    latitude: -15.4157279,
    longitude: 28.3425527,
    ownerName: "Kelvin Mwale",
    clientName: "Kelvin Mwale",
    clientEmail: "k.mwale@example.com",
    clientPhone: "+260970000006",
    clientSource: "Referral",
    clientSegment: "prospective_buyer",
    clientNrc: "623456/11/1",
    clientPassport: "ZMBP-006",
    clientTpin: "TPIN-0006",
    nationality: "Zambian",
    budgetMinAmount: "1800000.00",
    budgetMaxAmount: "2800000.00",
    budgetCurrency: "ZMW",
    clientNotes: "Needs a larger kitchen and a secure yard.",
    preferredLocation: "Kabulonga",
    propertyType: "Property",
    listingStatus: "reserved",
    availabilityStatus: "reserved",
    priceCents: 245000000,
    currency: "ZMW",
    listingCode: "LST-0006",
    listingType: "property",
    askingPriceAmount: "2450000.00",
    bedrooms: 5,
    bathrooms: 4,
    landSizeHa: "0.6200",
    zoning: "residential",
    landDesignation: "state_land",
    listingNotes: "Large family house with pool and staff quarters.",
    dealStage: "document_check",
    dealStatus: "open",
    dealType: "sale",
    dealValueCents: 245000000,
    dealOfferAmount: "2450000.00",
    dealCommissionPercent: "3.00",
    dealCommissionAmount: "73500.00",
    dealNotes: "Contract issued and awaiting final compliance docs.",
    workItemStatus: "in_progress",
    workItemTone: "warning",
    workItemKind: "Compliance",
    workItemDescription: "Confirm the property compliance checklist and inspection notes.",
    workItemPriority: "high",
    interactionType: "email",
    interactionOutcome: "Contract drafted",
    interactionSummary: "Buyer asked for compliance documents before signing.",
    interactionNextStep: "Send compliance pack and inspection photos.",
    planFrequency: "quarterly",
    planPeriods: 8,
    planStatus: "active",
    paymentPlanPrincipal: "2450000.00",
    paymentPlanDownPayment: "490000.00",
    installmentStatus: "paid",
    installmentAmountDue: "306250.00",
    installmentAmountPaid: "306250.00",
    leaseStatus: "ended",
    leaseStage: "lease_draft",
    leaseRentAmount: "15000.00",
    leaseBillingDay: 15,
    leaseDepositAmount: "3500.00",
    chargeStatus: "paid",
    chargeAmount: "15000.00",
    paymentMethod: "bank transfer",
    paymentAmount: "306250.00",
    paymentNotes: "Quarterly installment and inspection fee.",
    documentCategory: "site_plan",
    documentName: "Kabulonga Gardens 12 Site Plan",
    documentNotes: "Updated site plan verified by legal.",
    documentVerified: true,
    insightSeverity: "warn",
    insightStatus: "acknowledged",
    insightType: "compliance_gap",
    insightTitle: "Compliance docs pending",
    insightDescription: "The buyer still needs one compliance attachment.",
    insightRecommendedAction: "Collect the missing compliance certificate.",
    insightEvidence: "Inspection checklist has one unresolved item.",
    syncDeviceType: "mobile_app",
    appVersion: "1.0.1",
    syncErrorCode: "retry_pending",
    auditAction: "update",
  },
  {
    key: "kitwe-central-31",
    listingTitle: "Kitwe Central 31",
    area: "Kitwe Central",
    address: "31 Kitwe Central Drive, Kitwe",
    latitude: -12.8203689,
    longitude: 28.2155973,
    ownerName: "Ruth Soko",
    clientName: "Ruth Soko",
    clientEmail: "r.soko@example.com",
    clientPhone: "+260970000007",
    clientSource: "Walk-in",
    clientSegment: "past_lead",
    clientNrc: "723456/11/1",
    clientPassport: "ZMBP-007",
    clientTpin: "TPIN-0007",
    nationality: "Zambian",
    budgetMinAmount: "900000.00",
    budgetMaxAmount: "1600000.00",
    budgetCurrency: "ZMW",
    clientNotes: "Looking for a compact commercial property near transport routes.",
    preferredLocation: "Kitwe Central",
    propertyType: "Property",
    listingStatus: "available",
    availabilityStatus: "available",
    priceCents: 116000000,
    currency: "ZMW",
    listingCode: "LST-0007",
    listingType: "property",
    askingPriceAmount: "1160000.00",
    bedrooms: 3,
    bathrooms: 2,
    landSizeHa: "0.3100",
    zoning: "commercial",
    landDesignation: "state_land",
    listingNotes: "Street-facing property suited for mixed use.",
    dealStage: "offer_made",
    dealStatus: "open",
    dealType: "sale",
    dealValueCents: 116000000,
    dealOfferAmount: "1160000.00",
    dealCommissionPercent: "2.80",
    dealCommissionAmount: "32480.00",
    dealNotes: "Investor interested after the first viewing.",
    workItemStatus: "open",
    workItemTone: "info",
    workItemKind: "Site visit",
    workItemDescription: "Schedule the second viewing and verify access rights.",
    workItemPriority: "medium",
    interactionType: "site_visit",
    interactionOutcome: "Second viewing requested",
    interactionSummary: "Investor liked the frontage and asked for finance options.",
    interactionNextStep: "Share a finance summary and schedule a second visit.",
    planFrequency: "monthly",
    planPeriods: 18,
    planStatus: "active",
    paymentPlanPrincipal: "1160000.00",
    paymentPlanDownPayment: "232000.00",
    installmentStatus: "overdue",
    installmentAmountDue: "64444.44",
    installmentAmountPaid: "0.00",
    leaseStatus: "active",
    leaseStage: "active_tenancy",
    leaseRentAmount: "8500.00",
    leaseBillingDay: 3,
    leaseDepositAmount: "1800.00",
    chargeStatus: "overdue",
    chargeAmount: "8500.00",
    paymentMethod: "mobile money",
    paymentAmount: "64444.44",
    paymentNotes: "Installment overdue follow-up.",
    documentCategory: "offer_letter",
    documentName: "Kitwe Central 31 Offer Letter",
    documentNotes: "Initial offer letter issued after viewing.",
    documentVerified: false,
    insightSeverity: "critical",
    insightStatus: "open",
    insightType: "follow_up_gap",
    insightTitle: "Investor follow-up overdue",
    insightDescription: "The investor has not responded since the last visit.",
    insightRecommendedAction: "Follow up with a finance summary and next steps.",
    insightEvidence: "10 days since last contact.",
    syncDeviceType: "electron_desktop",
    appVersion: "1.0.2",
    syncErrorCode: "sync_ok",
    auditAction: "insert",
  },
  {
    key: "kabwe-hill-18",
    listingTitle: "Kabwe Hill 18",
    area: "Kabwe Hill",
    address: "18 Kabwe Hill Road, Kabwe",
    latitude: -14.5262739,
    longitude: 28.3420449,
    ownerName: "Patrick Tembo",
    clientName: "Patrick Tembo",
    clientEmail: "p.tembo@example.com",
    clientPhone: "+260970000008",
    clientSource: "Legacy import",
    clientSegment: "active_tenant",
    clientNrc: "823456/11/1",
    clientPassport: "ZMBP-008",
    clientTpin: "TPIN-0008",
    nationality: "Zambian",
    budgetMinAmount: "600000.00",
    budgetMaxAmount: "1200000.00",
    budgetCurrency: "USD",
    clientNotes: "Wants a mixed-use site with easy road access.",
    preferredLocation: "Kabwe Hill",
    propertyType: "Vacant land",
    listingStatus: "under_maintenance",
    availabilityStatus: "under_maintenance",
    priceCents: 7800000,
    currency: "USD",
    listingCode: "LST-0008",
    listingType: "vacant_land",
    askingPriceAmount: "78000.00",
    bedrooms: null,
    bathrooms: null,
    landSizeHa: "0.2600",
    zoning: "mixed",
    landDesignation: "customary_land",
    listingNotes: "Mixed-use site pending road access confirmation.",
    dealStage: "lost",
    dealStatus: "lost",
    dealType: "installment",
    dealValueCents: 7800000,
    dealOfferAmount: "78000.00",
    dealCommissionPercent: "2.20",
    dealCommissionAmount: "1716.00",
    dealNotes: "Investor withdrew after a zoning review.",
    workItemStatus: "done",
    workItemTone: "success",
    workItemKind: "Archive",
    workItemDescription: "Archive the lead and store the final notes.",
    workItemPriority: "low",
    interactionType: "negotiation",
    interactionOutcome: "Lead archived",
    interactionSummary: "Deal closed out after a zoning objection.",
    interactionNextStep: "Archive and no further follow-up.",
    planFrequency: "custom",
    planPeriods: 6,
    planStatus: "cancelled",
    paymentPlanPrincipal: "78000.00",
    paymentPlanDownPayment: "15600.00",
    installmentStatus: "due",
    installmentAmountDue: "13000.00",
    installmentAmountPaid: "0.00",
    leaseStatus: "ended",
    leaseStage: "closed",
    leaseRentAmount: "3200.00",
    leaseBillingDay: 8,
    leaseDepositAmount: "900.00",
    chargeStatus: "overdue",
    chargeAmount: "3200.00",
    paymentMethod: "cash",
    paymentAmount: "13000.00",
    paymentNotes: "Cancellation and archive settlement.",
    documentCategory: "site_plan",
    documentName: "Kabwe Hill 18 Site Plan",
    documentNotes: "Filed for reference after the deal was closed out.",
    documentVerified: true,
    insightSeverity: "info",
    insightStatus: "dismissed",
    insightType: "duplicate_client",
    insightTitle: "Duplicate client review",
    insightDescription: "Potential duplicate exists across imported contacts.",
    insightRecommendedAction: "Merge or archive the duplicate record.",
    insightEvidence: "Legacy import cluster still needs a merge decision.",
    syncDeviceType: "tablet",
    appVersion: "1.0.2",
    syncErrorCode: "sync_ok",
    auditAction: "delete",
  },
];

function makeUsersByRole() {
  return {
    primaryAdmin: userRows[0]!.id as string,
    agentNorth: userRows[1]!.id as string,
    agentSouth: userRows[2]!.id as string,
    finance: userRows[3]!.id as string,
    legal: userRows[4]!.id as string,
    auditor: userRows[5]!.id as string,
    opsAdmin: userRows[6]!.id as string,
    agentWest: userRows[7]!.id as string,
  };
}

function buildCaseRows(template: CaseTemplate, index: number, userIds: ReturnType<typeof makeUsersByRole>) {
  const listingId = `10000000-0000-4000-8000-00000000000${index + 1}`;
  const clientId = `20000000-0000-4000-8000-00000000000${index + 1}`;
  const dealId = `30000000-0000-4000-8000-00000000000${index + 1}`;
  const workItemId = `40000000-0000-4000-8000-00000000000${index + 1}`;
  const interactionId = `50000000-0000-4000-8000-00000000000${index + 1}`;
  const paymentPlanId = `60000000-0000-4000-8000-00000000000${index + 1}`;
  const installmentId = `61000000-0000-4000-8000-00000000000${index + 1}`;
  const leaseId = `70000000-0000-4000-8000-00000000000${index + 1}`;
  const rentalChargeId = `71000000-0000-4000-8000-00000000000${index + 1}`;
  const paymentId = `72000000-0000-4000-8000-00000000000${index + 1}`;
  const documentId = `73000000-0000-4000-8000-00000000000${index + 1}`;
  const insightId = `74000000-0000-4000-8000-00000000000${index + 1}`;
  const syncDeviceId = `75000000-0000-4000-8000-00000000000${index + 1}`;
  const eventId = `76000000-0000-4000-8000-00000000000${index + 1}`;
  const auditLogId = `77000000-0000-4000-8000-00000000000${index + 1}`;

  const createdAt = iso(index);
  const updatedAt = iso(index, 10);
  const interactionAt = iso(index - 1, 14);
  const dueAt = iso(index + 10, 9);
  const paymentAt = iso(index + 7, 8);
  const leaseStart = iso(index + 1, 9).slice(0, 10);
  const leaseEnd = iso(index + 365, 9).slice(0, 10);
  const periodMonth = iso(index + 20, 0);

  return {
    listing: {
      id: listingId,
      title: template.listingTitle,
      property_type: template.propertyType,
      status: template.listingStatus,
      price_cents: template.priceCents,
      currency: template.currency,
      owner_name: template.ownerName,
      created_by_user_id: userIds.primaryAdmin,
      listing_code: template.listingCode,
      type: template.listingType,
      availability_status: template.availabilityStatus,
      location_area: template.area,
      address: template.address,
      latitude: template.latitude,
      longitude: template.longitude,
      asking_price_amount: template.askingPriceAmount,
      asking_price_currency: template.currency,
      bedrooms: template.bedrooms,
      bathrooms: template.bathrooms,
      land_size_ha: template.landSizeHa,
      zoning: template.zoning,
      land_designation: template.landDesignation,
      assigned_agent_user_id: [userIds.agentNorth, userIds.agentSouth, userIds.agentWest][index % 3],
      internal_notes: template.listingNotes,
      last_modified_by_user_id: [userIds.opsAdmin, userIds.agentNorth, userIds.agentSouth, userIds.finance][index % 4],
      deleted_at: null,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    client: {
      id: clientId,
      full_name: template.clientName,
      email: template.clientEmail,
      phone: template.clientPhone,
      status: template.clientSegment === "active_tenant" ? "active" : template.clientSegment === "land_owner_seller" ? "archived" : "lead",
      source: template.clientSource,
      created_by_user_id: userIds.primaryAdmin,
      segment: template.clientSegment,
      nrc_number: template.clientNrc,
      passport_number: template.clientPassport,
      tpin: template.clientTpin,
      nationality: template.nationality,
      budget_min_amount: template.budgetMinAmount,
      budget_max_amount: template.budgetMaxAmount,
      budget_currency: template.budgetCurrency,
      notes: template.clientNotes,
      last_modified_by_user_id: [userIds.opsAdmin, userIds.agentNorth, userIds.agentSouth, userIds.finance][(index + 1) % 4],
      deleted_at: null,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    deal: {
      id: dealId,
      title: template.listingTitle,
      stage: template.dealStage,
      value_cents: template.dealValueCents,
      currency: template.currency,
      status: template.dealStatus,
      closed_at: template.dealStatus === "open" ? null : iso(index + 6, 11),
      listing_id: listingId,
      client_id: clientId,
      assigned_user_id: [userIds.agentNorth, userIds.agentSouth, userIds.agentWest][(index + 1) % 3],
      deal_name: `${template.listingTitle} ${template.dealType === "rental" ? "Rental" : "Deal"}`,
      deal_type: template.dealType,
      offer_amount: template.dealOfferAmount,
      offer_currency: template.currency,
      expected_close_at: iso(index + 20, 0),
      agent_user_id: [userIds.agentNorth, userIds.agentSouth, userIds.agentWest][index % 3],
      commission_percent: template.dealCommissionPercent,
      commission_amount: template.dealCommissionAmount,
      last_modified_by_user_id: userIds.finance,
      deleted_at: null,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    workItem: {
      id: workItemId,
      title: `${template.workItemKind} for ${template.listingTitle}`,
      kind: template.workItemKind,
      tone: template.workItemTone,
      status: template.workItemStatus,
      due_at: dueAt,
      assigned_user_id: [userIds.agentNorth, userIds.agentSouth, userIds.finance, userIds.legal][index % 4],
      created_by_user_id: userIds.primaryAdmin,
      work_type: template.workItemKind.toLowerCase().replace(/\s+/g, "_"),
      description: template.workItemDescription,
      priority: template.workItemPriority,
      owner_user_id: [userIds.agentNorth, userIds.agentSouth, userIds.finance, userIds.legal][index % 4],
      related_insight_id: insightId,
      entity_type: template.dealType === "rental" ? "lease" : "deal",
      entity_id: template.dealType === "rental" ? leaseId : dealId,
      completed_at: template.workItemStatus === "done" ? iso(index + 4, 15) : null,
      last_modified_by_user_id: [userIds.agentNorth, userIds.agentSouth, userIds.finance, userIds.legal][(index + 1) % 4],
      deleted_at: null,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    listingUtility: {
      listing_id: listingId,
      utility: ["water", "electricity", "internet", "sewer"][index % 4],
      created_at: createdAt,
    },
    clientPreferredLocation: {
      client_id: clientId,
      location_area: template.preferredLocation,
      created_at: createdAt,
    },
    dealListing: {
      deal_id: dealId,
      listing_id: listingId,
      created_at: createdAt,
    },
    interaction: {
      id: interactionId,
      summary: template.interactionSummary,
      client_id: clientId,
      listing_id: listingId,
      deal_id: dealId,
      type: template.interactionType,
      outcome: template.interactionOutcome,
      interaction_at: interactionAt,
      next_step: template.interactionNextStep,
      next_follow_up_at: iso(index + 2, 9),
      agent_user_id: [userIds.agentNorth, userIds.agentSouth, userIds.agentWest][index % 3],
      deleted_at: null,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    paymentPlan: {
      id: paymentPlanId,
      plan_name: `${template.listingTitle} Plan`,
      deal_id: dealId,
      client_id: clientId,
      principal_amount: template.paymentPlanPrincipal,
      down_payment_amount: template.paymentPlanDownPayment,
      currency: template.currency,
      frequency: template.planFrequency,
      periods: template.planPeriods,
      start_date: iso(index + 1, 9),
      status: template.planStatus,
      last_modified_by_user_id: userIds.finance,
      deleted_at: null,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    installmentScheduleItem: {
      id: installmentId,
      payment_plan_id: paymentPlanId,
      installment_number: index + 1,
      due_date: iso(index + 30, 9),
      amount_due: template.installmentAmountDue,
      amount_paid: template.installmentAmountPaid,
      paid_at: template.installmentStatus === "paid" ? paymentAt : null,
      status: template.installmentStatus,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    rentalLease: {
      id: leaseId,
      lease_name: `${template.listingTitle} Lease`,
      tenant_client_id: clientId,
      listing_id: listingId,
      lease_stage: template.leaseStage,
      start_date: leaseStart,
      end_date: leaseEnd,
      rent_amount: template.leaseRentAmount,
      currency: template.currency,
      billing_day: template.leaseBillingDay,
      deposit_amount: template.leaseDepositAmount,
      status: template.leaseStatus,
      last_modified_by_user_id: userIds.finance,
      deleted_at: null,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    rentalCharge: {
      id: rentalChargeId,
      lease_id: leaseId,
      period_month: periodMonth,
      due_date: iso(index + 31, 9),
      amount: template.chargeAmount,
      currency: template.currency,
      status: template.chargeStatus,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    payment: {
      id: paymentId,
      receipt_number: `RCPT-${String(index + 1).padStart(4, "0")}`,
      client_id: clientId,
      deal_id: dealId,
      payment_plan_id: paymentPlanId,
      installment_schedule_item_id: installmentId,
      lease_id: leaseId,
      rental_charge_id: rentalChargeId,
      paid_at: paymentAt,
      amount: template.paymentAmount,
      currency: template.currency,
      method: template.paymentMethod,
      notes: template.paymentNotes,
      recorded_by_user_id: userIds.finance,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    document: {
      id: documentId,
      document_name: template.documentName,
      category: template.documentCategory,
      listing_id: listingId,
      client_id: clientId,
      deal_id: dealId,
      blob_url: `https://blob.local/documents/${template.key}.pdf`,
      blob_key: `documents/${template.key}.pdf`,
      mime_type: "application/pdf",
      file_size_bytes: 100000 + index * 12345,
      is_verified: template.documentVerified,
      verified_at: template.documentVerified ? iso(index + 3, 12) : null,
      verified_by_user_id: template.documentVerified ? userIds.legal : userIds.auditor,
      notes: template.documentNotes,
      uploaded_by_user_id: [userIds.agentNorth, userIds.agentSouth, userIds.opsAdmin, userIds.agentWest][index % 4],
      deleted_at: null,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    insight: {
      id: insightId,
      insight_type: template.insightType,
      severity: template.insightSeverity,
      title: template.insightTitle,
      description: template.insightDescription,
      owner_user_id: [userIds.agentNorth, userIds.agentSouth, userIds.finance, userIds.legal][index % 4],
      status: template.insightStatus,
      entity_type: template.dealType === "rental" ? "lease" : "deal",
      entity_id: template.dealType === "rental" ? leaseId : dealId,
      evidence: JSON.stringify({
        summary: template.insightEvidence,
        case: template.key,
      }),
      recommended_action: template.insightRecommendedAction,
      due_at: iso(index + 10, 9),
      created_at: createdAt,
      updated_at: updatedAt,
    },
    syncDevice: {
      id: syncDeviceId,
      device_id: `demo-device-${String(index + 1).padStart(3, "0")}`,
      user_id: [userIds.agentNorth, userIds.agentSouth, userIds.finance, userIds.legal, userIds.opsAdmin][index % 5],
      device_type: template.syncDeviceType,
      app_version: template.appVersion,
      last_seen_at: iso(index, 17),
      created_at: createdAt,
      updated_at: updatedAt,
    },
    syncState: {
      device_id: syncDeviceId,
      last_sync_token: `sync-token-${String(index + 1).padStart(3, "0")}`,
      last_sync_at: iso(index, 18),
      last_error_code: template.syncErrorCode,
      last_error_at: template.syncErrorCode === "sync_ok" ? iso(index, 18) : iso(index, 16),
      consecutive_failures: template.syncErrorCode === "sync_ok" ? 0 : 1,
      updated_at: updatedAt,
    },
    event: {
      id: eventId,
      event_type: `${template.key}.seeded`,
      occurred_at: iso(index, 8),
      actor_user_id: [userIds.primaryAdmin, userIds.agentNorth, userIds.agentSouth, userIds.finance][index % 4],
      entity_type: template.dealType === "rental" ? "lease" : "deal",
      entity_id: template.dealType === "rental" ? leaseId : dealId,
      metadata: JSON.stringify({
        source: "seed",
        case: template.key,
        listingId,
        clientId,
      }),
      created_at: createdAt,
    },
    auditLog: {
      id: auditLogId,
      action: template.auditAction,
      occurred_at: iso(index, 19),
      actor_user_id: [userIds.primaryAdmin, userIds.agentNorth, userIds.finance, userIds.legal][index % 4],
      entity_type: template.dealType === "rental" ? "lease" : "deal",
      entity_id: template.dealType === "rental" ? leaseId : dealId,
      before_data: JSON.stringify({
        status: "draft",
        case: template.key,
      }),
      after_data: JSON.stringify({
        status: template.dealStatus,
        listingId,
        clientId,
      }),
      request_id: `seed-request-${String(index + 1).padStart(3, "0")}`,
      source: "seed",
      ip_address: "127.0.0.1",
      user_agent: "Contour seed",
    },
  };
}

export function buildContourSeedBlueprint(): ContourSeedBlueprint {
  const userIds = makeUsersByRole();
  const rows = cases.map((template, index) => buildCaseRows(template, index, userIds));

  return {
    users: userRows,
    listings: rows.map((row) => row.listing),
    clients: rows.map((row) => row.client),
    deals: rows.map((row) => row.deal),
    workItems: rows.map((row) => row.workItem),
    listingUtilities: rows.map((row) => row.listingUtility),
    clientPreferredLocations: rows.map((row) => row.clientPreferredLocation),
    dealListings: rows.map((row) => row.dealListing),
    interactions: rows.map((row) => row.interaction),
    paymentPlans: rows.map((row) => row.paymentPlan),
    installmentScheduleItems: rows.map((row) => row.installmentScheduleItem),
    rentalLeases: rows.map((row) => row.rentalLease),
    rentalCharges: rows.map((row) => row.rentalCharge),
    payments: rows.map((row) => row.payment),
    documents: rows.map((row) => row.document),
    insights: rows.map((row) => row.insight),
    syncDevices: rows.map((row) => row.syncDevice),
    syncState: rows.map((row) => row.syncState),
    events: rows.map((row) => row.event),
    auditLogs: rows.map((row) => row.auditLog),
  };
}
