import { PropertyMapItem } from "@/components/map/interactive-property-map";

export const MOCK_PROPERTIES: PropertyMapItem[] = [
  {
    id: "prop_01",
    title: "Executive 4-Bedroom Standalone Residence",
    slug: "executive-4-bed-kabulonga",
    listingType: "FOR_SALE",
    status: "AVAILABLE",
    ownershipType: "MANAGED_ON_BEHALF",
    askingPrice: 3500000,
    currency: "ZMW",
    bedrooms: 4,
    bathrooms: 3.5,
    plotSizeSqm: 2400,
    suburb: "Kabulonga",
    city: "Lusaka",
    latitude: -15.4215,
    longitude: 28.3345,
    standBoundary: [
      [-15.4211, 28.3341],
      [-15.4211, 28.3349],
      [-15.4219, 28.3349],
      [-15.4219, 28.3341],
    ],
    landmarkDirections: "200m off Kabulonga Road, near Centro Mall",
    description: "Immaculate standalone family residence set on a lush 2,400 m² plot in old Kabulonga. Features an expansive open-plan lounge with double-volume ceilings, chef's gourmet kitchen with granite countertops, private swimming pool, dedicated staff quarters, high-yield borehole, and automated 10kVA solar inverter system.",
    features: [
      "4 En-Suite Bedrooms",
      "3.5 Modern Bathrooms",
      "2,400 m² Landscaped Plot",
      "Private Swimming Pool",
      "Solar Inverter 10kVA",
      "High-Yield Borehole",
      "Electric Fence & Motorized Gate",
      "Double Garage & Staff Quarters",
    ],
    photos: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&auto=format&fit=crop&q=80",
    ],
    featuredPhoto: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&auto=format&fit=crop&q=80",
    assignedAgentName: "Tembo Mwape",
    assignedAgentPhone: "+260971234567",
  },
  {
    id: "prop_02",
    title: "Modern 3-Bedroom Townhouse in Gated Estate",
    slug: "modern-3-bed-leopards-hill",
    listingType: "FOR_RENT",
    status: "AVAILABLE",
    ownershipType: "MANAGED_ON_BEHALF",
    rentalPrice: 2200,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    plotSizeSqm: 650,
    suburb: "Leopards Hill",
    city: "Lusaka",
    latitude: -15.4480,
    longitude: 28.3810,
    standBoundary: [
      [-15.4477, 28.3806],
      [-15.4477, 28.3814],
      [-15.4483, 28.3814],
      [-15.4483, 28.3806],
    ],
    landmarkDirections: "Opposite American International School (AIS)",
    description: "Contemporary 3-bedroom executive townhouse located in a secure gated complex directly opposite the American International School. Offers turnkey diplomatic-grade accommodations with private patio, modern fitted kitchen, air conditioning throughout, communal swimming pool, borehole water, and 24/7 manned security.",
    features: [
      "3 Bedrooms (Master En-Suite)",
      "2 Modern Bathrooms",
      "Modern Fitted Kitchen",
      "Private Patio & Garden",
      "Communal Swimming Pool",
      "Borehole Water Supply",
      "Solar Inverter Backup",
      "24/7 Manned Security Gate",
    ],
    photos: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=80",
    ],
    featuredPhoto: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&auto=format&fit=crop&q=80",
    assignedAgentName: "Chipo Banda",
    assignedAgentPhone: "+260965987654",
  },
  {
    id: "prop_03",
    title: "Prime Commercial Office Space",
    slug: "prime-commercial-mass-media",
    listingType: "FOR_RENT",
    status: "AVAILABLE",
    ownershipType: "COMPANY_OWNED",
    rentalPrice: 35000,
    currency: "ZMW",
    plotSizeSqm: 450,
    suburb: "Mass Media",
    city: "Lusaka",
    latitude: -15.3980,
    longitude: 28.3120,
    standBoundary: [
      [-15.3975, 28.3115],
      [-15.3975, 28.3125],
      [-15.3985, 28.3125],
      [-15.3985, 28.3115],
    ],
    landmarkDirections: "Behind ZNBC Studios, off Alick Nkhata Road",
    description: "High-spec 450 m² commercial office floor located behind ZNBC Studios in the prestigious Mass Media business corridor. Features partitioned executive offices, open boardroom, server room with dedicated fiber connection, backup generator, ample customer parking, and round-the-clock security.",
    features: [
      "450 m² Usable Floor Area",
      "Executive Boardroom",
      "Dedicated Server Room",
      "High-Speed Fiber Optic",
      "Backup Standby Generator",
      "20 Dedicated Parking Bays",
      "24/7 CCTV & Security",
      "Paved Access Off Alick Nkhata",
    ],
    photos: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80",
    ],
    featuredPhoto: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80",
    assignedAgentName: "Tembo Mwape",
    assignedAgentPhone: "+260971234567",
  },
  {
    id: "prop_04",
    title: "5-Acre Commercial Development Plot",
    slug: "5-acre-plot-roma-park",
    listingType: "FOR_SALE",
    status: "SOLD",
    ownershipType: "MANAGED_ON_BEHALF",
    askingPrice: 850000,
    currency: "USD",
    plotSizeSqm: 20234,
    suburb: "Roma Park",
    city: "Lusaka",
    latitude: -15.3720,
    longitude: 28.3050,
    standBoundary: [
      [-15.3710, 28.3038],
      [-15.3710, 28.3062],
      [-15.3730, 28.3062],
      [-15.3730, 28.3038],
    ],
    landmarkDirections: "Inside Roma Park Mixed Use Development",
    description: "Prime 5-acre commercial and mixed-use development parcel situated within the master-planned Roma Park precinct. Fully serviced with tarred access roads, three-phase power connections, water mains, and clear title deed with zero encumbrances. Ideal for corporate headquarters, retail hub, or residential cluster.",
    features: [
      "5 Acres (20,234 m²)",
      "Fully Serviced Plot",
      "Tarred Road Frontage",
      "Three-Phase ZESCO Power",
      "Water Mains Connected",
      "Clean Freehold Title Deed",
      "Master-Planned Precinct",
      "Direct Access to Great East Road",
    ],
    photos: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&auto=format&fit=crop&q=80",
    ],
    featuredPhoto: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop&q=80",
    assignedAgentName: "Grace Banda",
    assignedAgentPhone: "+260977112233",
  },
  {
    id: "prop_05",
    title: "Luxury 2-Bedroom Serviced Apartment",
    slug: "luxury-2-bed-woodlands",
    listingType: "FOR_RENT",
    status: "RENTED",
    ownershipType: "MANAGED_ON_BEHALF",
    rentalPrice: 18000,
    currency: "ZMW",
    bedrooms: 2,
    bathrooms: 2,
    plotSizeSqm: 180,
    suburb: "Woodlands",
    city: "Lusaka",
    latitude: -15.4350,
    longitude: 28.3220,
    landmarkDirections: "Near Woodlands Stadium, off Independence Avenue",
    description: "Charming 2-bedroom fully furnished serviced apartment in the heart of Woodlands. Walking distance to Woodlands Stadium and shopping hubs. Fully equipped kitchen, weekly housekeeping, high-speed WiFi, solar water heating, and covered parking included.",
    features: [
      "2 Fully Furnished Bedrooms",
      "2 Modern Bathrooms",
      "Fully Equipped Kitchen",
      "High-Speed Fiber WiFi",
      "Weekly Housekeeping Service",
      "Solar Water Heating",
      "Covered Carport",
      "Automated Security Gate",
    ],
    photos: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&auto=format&fit=crop&q=80",
    ],
    featuredPhoto: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&auto=format&fit=crop&q=80",
    assignedAgentName: "Chipo Banda",
    assignedAgentPhone: "+260965987654",
  },
  {
    id: "prop_06",
    title: "Luxury 3-Bedroom Villa in Sunningdale",
    slug: "luxury-3-bed-sunningdale",
    listingType: "FOR_SALE",
    status: "AVAILABLE",
    ownershipType: "MANAGED_ON_BEHALF",
    askingPrice: 4200000,
    currency: "ZMW",
    bedrooms: 3,
    bathrooms: 3,
    plotSizeSqm: 1800,
    suburb: "Sunningdale",
    city: "Lusaka",
    latitude: -15.4180,
    longitude: 28.3410,
    landmarkDirections: "Off Bishops Road, Sunningdale",
    description: "Modern architectural 3-bedroom villa located on a quiet tree-lined avenue in Sunningdale. Features sleek minimalist interiors, wrap-around floor-to-ceiling glass windows, manicured lawn with indigenous trees, swimming pool, solar power system, and comprehensive perimeter security.",
    features: [
      "3 Spacious En-Suite Bedrooms",
      "3 Full Bathrooms",
      "1,800 m² Manicured Yard",
      "Swimming Pool & Sun Deck",
      "Floor-to-Ceiling Windows",
      "Full Solar Power System",
      "Deep Borehole System",
      "CCTV & Rapid Response Alarm",
    ],
    photos: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80",
    ],
    featuredPhoto: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=80",
    assignedAgentName: "Tembo Mwape",
    assignedAgentPhone: "+260971234567",
  },
];

export const MOCK_SALES = [
  {
    id: "sale_01",
    propertyTitle: "5-Acre Commercial Development Plot",
    propertySlug: "5-acre-plot-roma-park",
    suburb: "Roma Park",
    buyerName: "Zambezi Capital Holdings Ltd",
    buyerContact: "+260978112233",
    buyerNrcPassport: "NRC 452910/11/1",
    sellerName: "Roma Developments Ltd",
    salePrice: 850000,
    currency: "USD" as const,
    closingAgent: "Grace Banda",
    transferStatus: "COMPLETED",
    saleDate: "2026-07-28",
    agencyCommissionEarned: 42500,
    agentSplitPaid: 21250,
    ministryReference: "LUS/LAND/2026/8942-A",
  },
  {
    id: "sale_02",
    propertyTitle: "Executive 4-Bedroom Standalone Residence",
    propertySlug: "executive-4-bed-kabulonga",
    suburb: "Kabulonga",
    buyerName: "Nchimunya Mweene",
    buyerContact: "+260971889900",
    buyerNrcPassport: "NRC 223910/10/1",
    sellerName: "Hastings Banda",
    salePrice: 3500000,
    currency: "ZMW" as const,
    closingAgent: "Tembo Mwape",
    transferStatus: "PENDING_STATE_CONSENT",
    saleDate: "2026-08-15",
    agencyCommissionEarned: 175000,
    agentSplitPaid: 87500,
    ministryReference: "LUS/LAND/2026/1102-B",
  },
];

export type MockLease = {
  id: string;
  propertyTitle: string;
  propertySlug: string;
  suburb: string;
  tenantName: string;
  tenantPhone: string;
  monthlyRent: number;
  currency: "USD" | "ZMW" | "ZAR";
  managementFeePercent: number;
  status: "CURRENT" | "IN_ARREARS" | "ACTIVE" | "EXPIRED";
  leaseStartDate: string;
  leaseEndDate: string;
  lastPaymentDate: string;
  arrearsAmount: number;
  assignedAgent: string;
};

export const MOCK_LEASES: MockLease[] = [
  {
    id: "lease_01",
    propertyTitle: "Modern 3-Bedroom Townhouse (Leopards Hill)",
    propertySlug: "modern-3-bed-leopards-hill",
    suburb: "Leopards Hill",
    tenantName: "Mining Logistics Expat Family",
    tenantPhone: "+260975667788",
    monthlyRent: 2200,
    currency: "USD",
    managementFeePercent: 10,
    status: "CURRENT",
    leaseStartDate: "2026-06-15",
    leaseEndDate: "2027-06-14",
    lastPaymentDate: "2026-08-01",
    arrearsAmount: 0,
    assignedAgent: "Chipo Banda",
  },
  {
    id: "lease_02",
    propertyTitle: "Luxury 2-Bedroom Serviced Apartment",
    propertySlug: "luxury-2-bed-woodlands",
    suburb: "Woodlands",
    tenantName: "European Union Delegation Officer",
    tenantPhone: "+260967889900",
    monthlyRent: 18000,
    currency: "ZMW",
    managementFeePercent: 10,
    status: "IN_ARREARS",
    leaseStartDate: "2026-05-01",
    leaseEndDate: "2027-04-30",
    lastPaymentDate: "2026-07-02",
    arrearsAmount: 18000,
    assignedAgent: "Chipo Banda",
  },
];

export const MOCK_TRANSACTIONS = [
  {
    id: "tx_01",
    propertyTitle: "5-Acre Commercial Development Plot",
    grossValue: 850000,
    agencyCommissionAmount: 42500,
    agentSplitAmount: 21250,
    closingAgent: "Grace Banda",
    currency: "USD" as const,
    status: "RECEIVED" as const,
    date: "2026-07-28",
  },
  {
    id: "tx_02",
    propertyTitle: "Executive 4-Bedroom Standalone Residence",
    grossValue: 3500000,
    agencyCommissionAmount: 175000,
    agentSplitAmount: 87500,
    closingAgent: "Tembo Mwape",
    currency: "ZMW" as const,
    status: "PENDING_ESCROW" as const,
    date: "2026-08-15",
  },
  {
    id: "tx_03",
    propertyTitle: "Luxury 2-Bedroom Serviced Apartment",
    grossValue: 216000,
    agencyCommissionAmount: 18000,
    agentSplitAmount: 9000,
    closingAgent: "Chipo Banda",
    currency: "ZMW" as const,
    status: "RECEIVED" as const,
    date: "2026-08-01",
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: "doc_01",
    title: "Certificate of Title Deed Folio",
    propertyTitle: "Executive 4-Bedroom Standalone Residence",
    suburb: "Kabulonga",
    docType: "TITLE_DEED",
    fileSize: "2.4 MB",
    fileType: "PDF",
    uploadedAt: "2026-08-01",
    uploadedBy: "Grace Banda",
    isVerified: true,
    classification: "CONFIDENTIAL_LEGAL",
    registryFolio: "LUS/LAND/2026/8942-A",
  },
  {
    id: "doc_02",
    title: "Exclusive Sole Agency Mandate Contract",
    propertyTitle: "Executive 4-Bedroom Standalone Residence",
    suburb: "Kabulonga",
    docType: "MANDATE",
    fileSize: "1.1 MB",
    fileType: "PDF",
    uploadedAt: "2026-08-02",
    uploadedBy: "Tembo Mwape",
    isVerified: true,
    classification: "RESTRICTED_MANAGEMENT",
    registryFolio: "CTR-MND-2026-044",
  },
  {
    id: "doc_03",
    title: "Ministry of Lands Cadastral Survey Diagram",
    propertyTitle: "5-Acre Commercial Development Plot",
    suburb: "Roma Park",
    docType: "SURVEY",
    fileSize: "4.8 MB",
    fileType: "PDF",
    uploadedAt: "2026-08-05",
    uploadedBy: "Surveyor General",
    isVerified: true,
    classification: "PUBLIC_RECORD",
    registryFolio: "SD-LUS-8942",
  },
  {
    id: "doc_04",
    title: "PACRA Company Search & Title Verification",
    propertyTitle: "5-Acre Commercial Development Plot",
    suburb: "Roma Park",
    docType: "PACRA",
    fileSize: "850 KB",
    fileType: "PDF",
    uploadedAt: "2026-08-06",
    uploadedBy: "Legal Compliance",
    isVerified: true,
    classification: "RESTRICTED_MANAGEMENT",
    registryFolio: "PACRA-LUS-9910",
  },
];
