export const LUSAKA_SUBURBS = [
  "Avondale",
  "Bauleni",
  "Chalala",
  "Chalala South",
  "Chawama",
  "Chelstone",
  "Chilenje",
  "Foxdale",
  "Ibex Hill",
  "Kabulonga",
  "Kalikiliki",
  "Kamwala",
  "Kanyama",
  "Kasisi",
  "Leopard's Hill",
  "Libala",
  "Lilayi",
  "Longacres",
  "Lusaka West",
  "Makeni",
  "Manda Hill",
  "Mass Media",
  "Matero",
  "Meanwood",
  "Munali",
  "New Kasama",
  "Nyumba Yanga",
  "Olympia",
  "PHI",
  "Roma",
  "Roma Park",
  "Salama Park",
  "State Lodge",
  "Thornpark",
  "Twin Palm",
  "Woodlands",
  "Zimpat",
] as const satisfies readonly string[];
