"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Users } from "lucide-react";
type Member = { id: string; role: string; status: string; createdAt: string; user: { name: string; email: string; phone: string | null; role: string } };
export default function AgencyMembersPage({ params }: { params: Promise<{ id: string }> }) {
  const [organization, setOrganization] = useState<{ id: string; name: string } | null>(null); const [members, setMembers] = useState<Member[]>([]); const [message, setMessage] = useState("Loading agency people…");
  useEffect(() => { void params.then(({ id }) => fetch(`/api/admin/agencies/${id}/members`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load agency people."); setOrganization(data.organization); setMembers(data.members); setMessage(""); }).catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Unable to load agency people."))); }, [params]);
  return <main className="min-h-screen bg-editorial-bg px-4 py-6 font-geist text-editorial-black sm:px-8"><div className="mx-auto max-w-7xl space-y-7"><Link href={organization ? `/admin/agencies/${organization.id}` : "/admin/agencies"} className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-editorial-muted"><ArrowLeft className="h-4 w-4" /> Agency workspace</Link><header className="flex items-end justify-between border-b border-editorial-border pb-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-editorial-red">Agency operations // people</p><h1 className="mt-2 font-heading text-4xl font-bold uppercase">{organization?.name || "Agency people"}</h1><p className="mt-2 text-sm text-editorial-muted">Membership, role and account status within this agency.</p></div><Users className="hidden h-8 w-8 text-editorial-red sm:block" /></header>{message && <p className="text-sm text-editorial-muted">{message}</p>}<section className="overflow-x-auto border border-editorial-border bg-white"><table className="w-full min-w-[900px] text-left"><thead className="border-b border-editorial-border bg-editorial-paper"><tr className="text-[10px] font-bold uppercase tracking-widest text-editorial-muted"><th className="px-5 py-4">Person</th><th className="px-5 py-4">Agency role</th><th className="px-5 py-4">Account role</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Joined</th></tr></thead><tbody className="divide-y divide-editorial-border">{members.map((member) => <tr key={member.id}><td className="px-5 py-4"><div className="font-bold">{member.user.name}</div><div className="text-xs text-editorial-muted">{member.user.email}</div>{member.user.phone && <div className="font-mono text-[10px] text-editorial-muted">{member.user.phone}</div>}</td><td className="px-5 py-4 font-mono text-xs">{member.role}</td><td className="px-5 py-4 font-mono text-xs">{member.user.role}</td><td className="px-5 py-4"><span className={`text-xs font-bold uppercase ${member.status === "active" ? "text-emerald-700" : "text-red-700"}`}>{member.status}</span></td><td className="px-5 py-4 text-xs text-editorial-muted">{new Date(member.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table>{members.length === 0 && !message && <p className="p-8 text-center text-sm text-editorial-muted">No members are attached to this agency.</p>}</section></div></main>;
}
