"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Headset } from "lucide-react";
type SupportSession = { id: string; mode: string; reason: string; expiresAt: string; revokedAt: string | null; createdAt: string; organization: { id: string; name: string; slug: string } };
export default function SupportAccessPage() {
  const [sessions, setSessions] = useState<SupportSession[]>([]); const [message, setMessage] = useState("Loading support sessions…");
  const load = useCallback(async () => { const response = await fetch("/api/admin/support-access"); const data = await response.json(); setSessions(data.sessions || []); setMessage(response.ok ? "" : data.error || "Unable to load support sessions."); }, []);
  useEffect(() => { void load(); }, [load]);
  async function revoke(id: string) { if (!window.confirm("End this support access session now?")) return; const response = await fetch(`/api/admin/support-access/${id}/revoke`, { method: "POST" }); const data = await response.json(); setMessage(response.ok ? "Support session ended and audited." : data.error || "Unable to end session."); if (response.ok) await load(); }
  return <main className="min-h-screen bg-editorial-bg px-4 py-6 font-geist text-editorial-black sm:px-8"><div className="mx-auto max-w-7xl space-y-7"><Link href="/admin" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-editorial-muted"><ArrowLeft className="h-4 w-4" /> Control Plane</Link><header className="flex items-end justify-between border-b border-editorial-border pb-5"><div><div className="flex items-center gap-3"><Headset className="h-5 w-5 text-editorial-red" /><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-editorial-red">Controlled operator access</p></div><h1 className="mt-2 font-heading text-4xl font-bold uppercase">Support access</h1><p className="mt-2 text-sm text-editorial-muted">Review your active and recent time-limited agency sessions.</p></div><Link href="/admin/agencies" className="bg-editorial-black px-4 py-3 text-xs font-bold uppercase tracking-wider text-white">Start from agency</Link></header>{message && <p className="text-sm text-editorial-muted">{message}</p>}<section className="overflow-x-auto border border-editorial-border bg-white"><table className="w-full min-w-[900px] text-left"><thead className="border-b border-editorial-border bg-editorial-paper"><tr className="text-[10px] font-bold uppercase tracking-widest text-editorial-muted"><th className="px-5 py-4">Agency</th><th className="px-5 py-4">Mode</th><th className="px-5 py-4">Started</th><th className="px-5 py-4">Expires</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Action</th></tr></thead><tbody className="divide-y divide-editorial-border">{sessions.map((item) => { const active = !item.revokedAt && new Date(item.expiresAt) > new Date(); return <tr key={item.id}><td className="px-5 py-4"><Link href={`/admin/support-access/${item.id}`} className="font-bold hover:text-contour-red">{item.organization.name}</Link><div className="font-mono text-[10px] text-editorial-muted">/{item.organization.slug}</div></td><td className="px-5 py-4 font-mono text-xs">{item.mode}</td><td className="px-5 py-4 text-xs text-editorial-muted">{new Date(item.createdAt).toLocaleString()}</td><td className="px-5 py-4 text-xs text-editorial-muted">{new Date(item.expiresAt).toLocaleString()}</td><td className="px-5 py-4 text-xs font-bold uppercase"><span className={active ? "text-emerald-700" : "text-editorial-muted"}>{item.revokedAt ? "Ended" : active ? "Active" : "Expired"}</span></td><td className="px-5 py-4">{active && <button onClick={() => void revoke(item.id)} className="border border-editorial-red px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-editorial-red">End session</button>}</td></tr>; })}</tbody></table>{sessions.length === 0 && !message && <p className="p-8 text-center text-sm text-editorial-muted">No support sessions yet.</p>}</section></div></main>;
}
