"use client";

import { useState } from "react";

type SubscriptionType = "TRIAL" | "STARTER" | "GROWTH" | "ENTERPRISE" | "LIFETIME" | "PERCENTAGE_DISCOUNT" | "AMOUNT_DISCOUNT";

export function AgencySubscriptionEditor({ organizationId, currency, currentTier, currentStatus, trialEndsAt, onSaved }: { organizationId: string; currency: string; currentTier: string; currentStatus: string; trialEndsAt: string | null; onSaved: () => void }) {
  const [open, setOpen] = useState(false); const [type, setType] = useState<SubscriptionType>(currentStatus === "trialing" ? "TRIAL" : currentTier === "LIFETIME" ? "LIFETIME" : currentTier as SubscriptionType); const [trialDate, setTrialDate] = useState(trialEndsAt?.slice(0, 10) || ""); const [discount, setDiscount] = useState(""); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function save() { if (reason.trim().length < 20) { setMessage("Give a reason of at least 20 characters."); return; } setSaving(true); const response = await fetch(`/api/admin/agencies/${organizationId}/subscription`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ type, trialEndsAt: trialDate || undefined, discountValue: discount ? Number(discount) : undefined, reason }) }); const data = await response.json(); setSaving(false); if (!response.ok) { setMessage(data.error || "Unable to update subscription."); return; } setMessage("Subscription updated and audited."); onSaved(); }
  return <><button onClick={() => setOpen(true)} className="border border-editorial-border px-3 py-2 text-[10px] font-bold uppercase hover:border-editorial-red">Edit subscription</button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" role="dialog" aria-modal="true" aria-labelledby="subscription-editor-title"><div className="w-full max-w-lg space-y-4 border border-editorial-border bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-editorial-red">Agency billing</p><h2 id="subscription-editor-title" className="mt-2 font-serif text-2xl font-bold">Edit subscription</h2><p className="mt-1 text-xs text-editorial-muted">Amounts use this agency's default currency: {currency}.</p></div><button onClick={() => setOpen(false)} aria-label="Close" className="text-xl">×</button></div><select value={type} onChange={(event) => setType(event.target.value as SubscriptionType)} className="h-11 w-full border border-editorial-border px-3 text-sm"><option value="TRIAL">Trial</option><option value="STARTER">Starter agency</option><option value="GROWTH">Growth agency</option><option value="ENTERPRISE">Enterprise agency</option><option value="LIFETIME">Lifetime access</option><option value="PERCENTAGE_DISCOUNT">Percentage discount</option><option value="AMOUNT_DISCOUNT">Amount discount</option></select>{type === "TRIAL" && <label className="block text-xs">Trial ends<input type="date" value={trialDate} onChange={(event) => setTrialDate(event.target.value)} className="mt-1 h-11 w-full border border-editorial-border px-3" /></label>}{["PERCENTAGE_DISCOUNT", "AMOUNT_DISCOUNT"].includes(type) && <label className="block text-xs">{type === "PERCENTAGE_DISCOUNT" ? "Discount percentage" : `Discount amount (${currency})`}<input type="number" min="0.01" step="0.01" value={discount} onChange={(event) => setDiscount(event.target.value)} className="mt-1 h-11 w-full border border-editorial-border px-3 font-mono" /></label>}<textarea value={reason} onChange={(event) => setReason(event.target.value)} minLength={20} placeholder="Reason for this audited change (minimum 20 characters)" className="min-h-24 w-full border border-editorial-border p-3 text-sm" />{message && <p className="text-xs text-editorial-muted">{message}</p>}<div className="flex justify-end gap-2"><button onClick={() => setOpen(false)} className="border border-editorial-border px-4 py-2 text-xs font-bold uppercase">Cancel</button><button disabled={saving} onClick={() => void save()} className="bg-editorial-black px-4 py-2 text-xs font-bold uppercase text-white disabled:opacity-50">{saving ? "Saving…" : "Save audited change"}</button></div></div></div>}</>;
}
