"use client";
import { useState } from "react";

export function AgencyAccountActions({ organizationId, accountStatus, onSaved }: { organizationId: string; accountStatus: string; onSaved: () => void }) {
  const [action, setAction] = useState<"SUSPENDED" | "ACTIVE" | "DELETE" | "RESTORE" | null>(null); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const minimum = action === "DELETE" ? 30 : 20;
  async function submit() { if (!action || reason.trim().length < minimum) return; setBusy(true); const endpoint = action === "DELETE" ? "/api/admin/agencies/deletion" : action === "RESTORE" ? "/api/admin/agencies/deletion/restore" : "/api/admin/agencies/state"; const response = await fetch(endpoint, { method: action === "DELETE" || action === "RESTORE" ? "POST" : "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(action === "DELETE" ? { organizationId, confirmation: "DELETE AGENCY", reason: reason.trim() } : action === "RESTORE" ? { organizationId, reason: reason.trim() } : { organizationId, accountStatus: action, reason: reason.trim() }) }); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { window.alert(data.error || "Unable to update agency account."); return; } setAction(null); setReason(""); onSaved(); }
  const title = action === "DELETE" ? "Schedule agency deletion" : action === "RESTORE" ? "Restore agency" : action === "ACTIVE" ? "Reactivate agency" : "Suspend agency";
  return <><div className="flex flex-wrap gap-2">{accountStatus === "DELETION_PENDING" ? <button type="button" onClick={() => setAction("RESTORE")} className="border border-emerald-300 px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-emerald-700">Restore agency</button> : <><button type="button" onClick={() => setAction(accountStatus === "ACTIVE" ? "SUSPENDED" : "ACTIVE")} className="border border-editorial-border px-3 py-2 text-[10px] font-bold uppercase tracking-wider">{accountStatus === "ACTIVE" ? "Suspend account" : "Reactivate account"}</button><button type="button" onClick={() => setAction("DELETE")} className="border border-red-300 px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-red-700">Schedule deletion</button></>}</div>{action && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-lg border border-editorial-border bg-white p-6 shadow-2xl"><p className="text-[10px] font-bold uppercase tracking-widest text-editorial-red">Governed account action</p><h2 className="mt-2 font-serif text-2xl font-bold">{title}</h2><p className="mt-2 text-sm text-editorial-muted">{action === "DELETE" ? "This locks access and starts a 30-day recovery window. It does not immediately erase data." : "This action is audited and changes access for the whole agency."}</p><textarea value={reason} onChange={(event) => setReason(event.target.value)} minLength={minimum} placeholder={`Reason (minimum ${minimum} characters)`} className="mt-5 min-h-24 w-full border border-editorial-border p-3 text-sm" /><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setAction(null)} className="border border-editorial-border px-4 py-2 text-xs font-bold uppercase">Cancel</button><button type="button" disabled={busy || reason.trim().length < minimum} onClick={() => void submit()} className="bg-editorial-black px-4 py-2 text-xs font-bold uppercase text-white disabled:opacity-50">{busy ? "Saving…" : "Confirm action"}</button></div></div></div>}</>;
}
