ALTER TYPE "InquiryStatus" ADD VALUE IF NOT EXISTS 'QUALIFIED';
ALTER TYPE "InquiryStatus" ADD VALUE IF NOT EXISTS 'VIEWING_OR_OFFER';
ALTER TYPE "InquiryStatus" ADD VALUE IF NOT EXISTS 'VERIFICATION_CLOSING';
