"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Eye, ShieldCheck } from "lucide-react";

type SupportView = { expiresAt: string; organization: { name: string; subscriptionTier: string; subscriptionStatus: string; _count: { members: number; properties: number; inquiries: number } } };

export default function SupportAccessView({ params }: { params: Promise<{ id: string }> }) {
  const [data, setData] = useState<SupportView | null>(null);
  const [message, setMessage] = useState("Loading read-only support session…");
  useEffect(() => { void params.then(({ id }) => fetch(`/api/admin/support-access/${id}`).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); setMessage(""); }).catch((error: Error) => setMessage(error.message))); }, [params]);
  async function endSession() { const id = (await params).id; await fetch(`/api/admin/support-access/${id}`, { method: "DELETE" }); window.location.href = "/admin/agencies"; }
  return <main className="min-h-screen bg-editorial-bg px-4 py-6 font-geist text-editorial-black sm:px-8"><div className="mx-auto max-w-5xl space-y-7"><Link href="/admin/agencies" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-editorial-muted hover:text-editorial-red"><ArrowLeft className="h-4 w-4" /> Agency directory</Link><header className="border border-editorial-border bg-[#282828] p-6 text-white"><div className="flex items-center gap-3"><Eye className="h-5 w-5 text-[#fa3600]" /><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#fa3600]">Support access // view only</p></div><h1 className="mt-3 font-heading text-4xl font-bold uppercase">Agency support view</h1><p className="mt-2 text-sm text-white/70">This session cannot mutate agency data. It expires automatically and every access is audited.</p></header>{message && <p className="text-sm text-editorial-muted">{message}</p>}{data && <><section className="grid gap-4 md:grid-cols-3">{[["Agency", data.organization.name], ["Subscription", `${data.organization.subscriptionTier} · ${data.organization.subscriptionStatus}`], ["Expires", new Date(data.expiresAt).toLocaleString()]].map(([label, value]) => <div key={label} className="border border-editorial-border bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-editorial-muted">{label}</p><p className="mt-3 font-mono text-sm">{value}</p></div>)}</section><section className="border border-editorial-border bg-white p-6"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-700" /><h2 className="font-serif text-2xl font-bold">Read-only agency snapshot</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-3">{[["Members", data.organization._count.members], ["Properties", data.organization._count.properties], ["Inquiries", data.organization._count.inquiries]].map(([label, value]) => <div key={label} className="bg-editorial-paper p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-editorial-muted">{label}</p><p className="mt-2 font-mono text-2xl font-bold">{value}</p></div>)}</div></section><button onClick={() => void endSession()} className="bg-editorial-black px-5 py-3 text-xs font-bold uppercase tracking-wider text-white hover:bg-editorial-red">End support session</button></>}</div></main>;
}
