"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Activity, Building2, CreditCard, DollarSign, Home, RefreshCw, ShieldCheck, Users } from "lucide-react";

type Overview = { range: { from: string; to: string }; kpis: { agencies: { total: number; newInRange: number }; users: { total: number; newInRange: number }; properties: { total: number; newInRange: number }; closedProperties: { total: number }; inquiries: { total: number; newInRange: number }; subscriptions: { active: number; trialing: number; pastDue: number }; recurringRevenue: { mrrByCurrency: Record<string, number>; arrByCurrency: Record<string, number> }; collectedRevenue: { totalByCurrency: Record<string, number> } }; subscriptionMix: Array<{ tier: string; name: string; subscribers: number; mrrByCurrency: Record<string, number> }>; series: Array<{ date: string; revenue: Record<string, number>; inquiries: number; closed: number }>; team: Array<{ memberId: string; name: string; email: string; inquiries: number; closedProperties: number; valueByCurrency: Record<string, number> }> };
const money = (values: Record<string, number>) => Object.entries(values).map(([currency, value]) => `${currency} ${value.toLocaleString(undefined, { maximumFractionDigits: 0 })}`).join(" · ") || "—";

export default function AdminPage() {
  const [range, setRange] = useState("30d"); const [data, setData] = useState<Overview | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { setLoading(true); setError(""); fetch(`/api/admin/overview?range=${range}`).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error || "Unable to load overview."); setData(result); }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, [range]);
  const kpis = data?.kpis;
  const cards = [["Agencies", kpis?.agencies.total, `+${kpis?.agencies.newInRange || 0} in range`, Building2], ["Users", kpis?.users.total, `+${kpis?.users.newInRange || 0} in range`, Users], ["Properties", kpis?.properties.total, `+${kpis?.properties.newInRange || 0} in range`, Home], ["Closed properties", kpis?.closedProperties.total, "completed transactions", ShieldCheck], ["New inquiries", kpis?.inquiries.newInRange, `${kpis?.inquiries.total || 0} all time`, Activity], ["Active subscriptions", kpis?.subscriptions.active, `${kpis?.subscriptions.trialing || 0} trial · ${kpis?.subscriptions.pastDue || 0} due`, CreditCard]] as const;
  return <main className="min-h-screen bg-editorial-bg px-4 py-5 font-sans text-editorial-black sm:px-8 lg:px-12"><div className="mx-auto w-full max-w-7xl space-y-6 pb-20">
    <header className="flex flex-col gap-4 border-b border-editorial-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-editorial-red">Platform operations // overview</p><h1 className="mt-2 text-3xl font-bold uppercase tracking-tight sm:text-5xl">Control Plane</h1><p className="mt-2 max-w-2xl text-sm text-editorial-muted">Live platform scale, subscription economics, agency activity, and operator performance.</p></div><div className="flex items-center gap-2"><select value={range} onChange={(event) => setRange(event.target.value)} className="h-10 border border-editorial-border bg-white px-3 text-xs font-bold uppercase tracking-wider"><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select><Link href="/dashboard" className="hidden text-xs font-bold uppercase tracking-wider text-editorial-muted hover:text-editorial-red sm:inline">Workspace ↗</Link></div></header>
    {error && <div className="flex items-center justify-between border border-red-200 bg-red-50 p-4 text-sm text-red-800"><span>{error}</span><button onClick={() => setRange((value) => value)} className="inline-flex items-center gap-2 text-xs font-bold uppercase"><RefreshCw className="h-4 w-4" /> Retry</button></div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label, value, note, Icon]) => <article key={label} className="border border-editorial-border bg-white p-4 shadow-subtle"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-widest text-editorial-muted">{label}</span><Icon className="h-4 w-4 text-editorial-red" /></div><div className="mt-4 text-3xl font-bold">{loading ? "…" : value ?? 0}</div><p className="mt-1 text-xs text-editorial-muted">{note}</p></article>)}</section>
    <section className="grid gap-4 lg:grid-cols-[1.4fr_1fr]"><article className="border border-editorial-border bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-editorial-red">Revenue performance</p><h2 className="mt-1 text-xl font-bold">Collected revenue</h2></div><DollarSign className="h-5 w-5 text-editorial-red" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Metric label="MRR" value={money(kpis?.recurringRevenue.mrrByCurrency || {})} /><Metric label="ARR" value={money(kpis?.recurringRevenue.arrByCurrency || {})} /><Metric label="Cash collected" value={money(kpis?.collectedRevenue.totalByCurrency || {})} /><Metric label="Reporting window" value={data ? `${new Date(data.range.from).toLocaleDateString()} – ${new Date(data.range.to).toLocaleDateString()}` : "…"} /></div><div className="mt-6 flex h-36 items-end gap-1 border-b border-l border-editorial-border px-2">{(data?.series || []).slice(-30).map((point) => { const total = Object.values(point.revenue).reduce((sum, value) => sum + value, 0); const max = Math.max(...(data?.series || []).map((item) => Object.values(item.revenue).reduce((sum, value) => sum + value, 0)), 1); return <div key={point.date} title={`${point.date}: ${money(point.revenue)}`} className="flex-1 bg-editorial-red/70 hover:bg-editorial-red" style={{ height: `${Math.max(3, (total / max) * 100)}%` }} />; })}</div><p className="mt-2 text-[10px] text-editorial-muted">Daily collected revenue · hover bars for detail</p></article><article className="border border-editorial-border bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-editorial-red">Subscription mix</p><h2 className="mt-1 text-xl font-bold">Plans in the system</h2><div className="mt-5 space-y-3">{(data?.subscriptionMix || []).map((tier) => <Link key={tier.tier} href={`/admin/agencies?status=active&tier=${tier.tier}`} className="flex items-center justify-between border-b border-editorial-border pb-3 hover:text-editorial-red"><div><p className="font-bold">{tier.name}</p><p className="text-xs text-editorial-muted">{money(tier.mrrByCurrency)} MRR</p></div><span className="text-xl font-bold">{tier.subscribers}</span></Link>)}{!loading && !data?.subscriptionMix.length && <p className="text-sm text-editorial-muted">No active tier catalog data.</p>}</div></article></section>
    <section className="grid gap-4 lg:grid-cols-2"><article className="border border-editorial-border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-editorial-red">Team board</p><h2 className="mt-1 text-xl font-bold">Operator performance</h2></div><Users className="h-5 w-5 text-editorial-red" /></div><div className="mt-4 divide-y divide-editorial-border">{(data?.team || []).map((member) => <div key={member.memberId} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-bold">{member.name}</p><p className="truncate text-xs text-editorial-muted">{member.email}</p></div><div className="flex gap-5 text-right text-xs"><span><strong className="block text-lg">{member.inquiries}</strong> inquiries</span><span><strong className="block text-lg">{member.closedProperties}</strong> closed</span><span><strong className="block text-lg">{money(member.valueByCurrency)}</strong> value</span></div></div>)}{!loading && !data?.team.length && <p className="py-6 text-sm text-editorial-muted">No team activity in this period.</p>}</div></article><article className="border border-editorial-border bg-[#282828] p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-widest text-[#fa3600]">Activity pulse</p><h2 className="mt-1 text-xl font-bold">Platform throughput</h2><div className="mt-5 space-y-4">{[["Inquiries", data?.series.reduce((sum, item) => sum + item.inquiries, 0) || 0], ["Properties closed", data?.series.reduce((sum, item) => sum + item.closed, 0) || 0], ["Revenue days", data?.series.filter((item) => Object.keys(item.revenue).length > 0).length || 0]].map(([label, value]) => <div key={label} className="flex items-end justify-between border-b border-white/20 pb-3"><span className="text-sm text-white/70">{label}</span><strong className="text-3xl">{loading ? "…" : value}</strong></div>)}</div><p className="mt-5 text-xs leading-5 text-white/60">Use the range control to compare daily, weekly, and quarterly momentum.</p></article></section>
    <section className="border border-editorial-border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-editorial-muted">Governance</p><h2 className="mt-1 text-xl font-bold">Privileged access remains deliberate</h2></div><ShieldCheck className="h-5 w-5 text-emerald-700" /></div><p className="mt-2 max-w-3xl text-sm leading-6 text-editorial-muted">Support access, impersonation, billing overrides, account locks, and deletion remain scoped, reasoned, expiring, and audited.</p></section>
  </div></main>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="bg-editorial-paper p-3"><p className="text-[10px] font-bold uppercase tracking-widest text-editorial-muted">{label}</p><p className="mt-2 text-sm font-bold">{value}</p></div>; }
