import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
const migration = readFileSync(resolve("prisma/migrations/20261005071000_statement_documents/migration.sql"), "utf8");
const historical = readFileSync(resolve("prisma/migrations/20260924140000_landlord_statement_ledger/migration.sql"), "utf8");
describe("landlord revision migration compatibility", () => {
  it("removes the actual historical PostgreSQL-truncated uniqueness index", () => {
    const literal = historical.match(/CREATE UNIQUE INDEX "([^"]+)"/)?.[1];
    expect(literal).toBeDefined();
    expect(migration).toContain(`DROP INDEX IF EXISTS "${literal!.slice(0, 63)}"`);
  });
  it("also supports a baseline generated by Prisma and preserves revision uniqueness", () => {
    expect(migration).toContain('DROP INDEX IF EXISTS "landlord_statement_organizationId_propertyId_statementYear__key"');
    expect(migration).toContain('("organizationId", "propertyId", "statementYear", "statementMonth", "revision")');
    expect(migration.trim()).toMatch(/^BEGIN;[\s\S]*COMMIT;$/);
  });
});
