import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url().default("postgresql://postgres:postgres@localhost:5432/contour_db"),
    // No default — must be set explicitly. Use: openssl rand -base64 32
    BETTER_AUTH_SECRET: z.string().min(32),
    BETTER_AUTH_URL: z.string().url().default("http://localhost:3000"),
    GOOGLE_CLIENT_ID: z.string().optional(),
    GOOGLE_CLIENT_SECRET: z.string().optional(),
    // Separate secret for Dify agent-to-app bearer auth. Must NOT be the same as BETTER_AUTH_SECRET.
    DIFY_MASTER_SECRET: z.string().min(32).optional(),
    LENCO_API_KEY: z.string().optional(),
    LENCO_API_URL: z.string().url().default("https://api.lenco.co/access/v2"),
    LENCO_ENVIRONMENT: z.enum(["sandbox", "production"]).default("sandbox"),
    REDIS_URL: z.string().optional(),
    POWERSYNC_URL: z.string().url().optional(),
    POWERSYNC_JWT_SECRET: z.string().min(32).optional(),
    LOG_LEVEL: z.string().optional(),
    S3_ENDPOINT: z.string().optional(),
    S3_REGION: z.string().default("auto"),
    S3_BUCKET_NAME: z.string().optional(),
    S3_ACCESS_KEY_ID: z.string().optional(),
    S3_SECRET_ACCESS_KEY: z.string().optional(),
    S3_PUBLIC_DOMAIN: z.string().optional(),
    CONTOUR_CONTROL_PLANE_OWNER_EMAILS: z.string().default(""),
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
    NEXT_PUBLIC_DEV_MODE: z.string().default("false"),
    NEXT_PUBLIC_MAP_DEFAULT_LAT: z.string().default("-15.4167"),
    NEXT_PUBLIC_MAP_DEFAULT_LNG: z.string().default("28.2833"),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    DIFY_MASTER_SECRET: process.env.DIFY_MASTER_SECRET,
    LENCO_API_KEY: process.env.LENCO_API_KEY,
    LENCO_API_URL: process.env.LENCO_API_URL,
    LENCO_ENVIRONMENT: process.env.LENCO_ENVIRONMENT as "sandbox" | "production" | undefined,
    REDIS_URL: process.env.REDIS_URL,
    POWERSYNC_URL: process.env.POWERSYNC_URL,
    POWERSYNC_JWT_SECRET: process.env.POWERSYNC_JWT_SECRET,
    LOG_LEVEL: process.env.LOG_LEVEL,
    S3_ENDPOINT: process.env.S3_ENDPOINT,
    S3_REGION: process.env.S3_REGION,
    S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
    S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
    S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
    S3_PUBLIC_DOMAIN: process.env.S3_PUBLIC_DOMAIN,
    CONTOUR_CONTROL_PLANE_OWNER_EMAILS: process.env.CONTOUR_CONTROL_PLANE_OWNER_EMAILS,
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_DEV_MODE: process.env.NEXT_PUBLIC_DEV_MODE,
    NEXT_PUBLIC_MAP_DEFAULT_LAT: process.env.NEXT_PUBLIC_MAP_DEFAULT_LAT,
    NEXT_PUBLIC_MAP_DEFAULT_LNG: process.env.NEXT_PUBLIC_MAP_DEFAULT_LNG,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
