"use client";
import { useState } from "react";
import { paymentInstructionSchema } from "@/lib/statements/document";
import type { z } from "zod";
export type PaymentInstruction = z.infer<typeof paymentInstructionSchema> & { id: string };
const empty = { label: "", method: "BANK_TRANSFER" as PaymentInstruction["method"], active: true, details: { accountHolder: "", bank: "", accountNumber: "", branch: "", recipientPhone: "", reference: "", instructions: "" } };
export function PaymentInstructionsEditor({ instructions, onSaved }: { instructions: PaymentInstruction[]; onSaved: () => void }) {
  const [editing, setEditing] = useState(false), [form, setForm] = useState<z.infer<typeof paymentInstructionSchema>>(empty), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const fields: Array<[keyof typeof empty.details, string]> = form.method === "BANK_TRANSFER" ? [["accountHolder", "Account holder"], ["bank", "Bank"], ["accountNumber", "Account number"], ["branch", "Branch / code"], ["reference", "Payment reference"], ["instructions", "Additional instructions"]] : form.method.startsWith("MOBILE_MONEY") ? [["accountHolder", "Recipient name"], ["recipientPhone", "Recipient phone"], ["reference", "Payment reference"], ["instructions", "Additional instructions"]] : [["instructions", "Payment instructions"], ["reference", "Payment reference"]];
  const save = async (e: React.FormEvent) => {
    e.preventDefault(); const valid = paymentInstructionSchema.safeParse(form); if (!valid.success) { setError(valid.error.issues.map(i => `${i.path.join(" ")}: ${i.message}`).join(" · ")); return; }
    setBusy(true); setError(""); try { const r = await fetch("/api/statement-payment-instructions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(valid.data) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to save agency instructions."); setEditing(false); onSaved(); } catch(e) { setError(e instanceof Error ? e.message : "Unable to save."); } finally { setBusy(false); }
  };
  return <section className="space-y-3 border-t border-editorial-border pt-4"><p className="text-sm font-semibold">Agency payment instructions</p><div className="flex flex-wrap gap-2">{instructions.map(i => <button type="button" key={i.id} className="min-h-11 border border-editorial-border px-3 text-xs" onClick={() => { setForm(i); setError(""); setEditing(true); }}>Edit {i.label}{!i.active ? " (inactive)" : ""}</button>)}<button type="button" className="min-h-11 border border-editorial-border px-3 text-xs" onClick={() => { setForm(empty); setError(""); setEditing(true); }}>Add payment instructions</button></div>
    {editing && <form onSubmit={save} className="space-y-3 bg-editorial-paper p-4"><p className="text-xs text-editorial-muted">Changes apply to future statements. Saved statements retain their original instructions.</p>{error && <p role="alert" className="text-sm text-red-800">{error}</p>}<fieldset disabled={busy} className="space-y-3"><label className="block text-sm">Label<input required maxLength={80} value={form.label} onChange={e => setForm({ ...form, label: e.target.value })} className="mt-1 min-h-11 w-full border p-2" /></label><label className="block text-sm">Payment method<select value={form.method} onChange={e => setForm({ ...form, method: e.target.value as PaymentInstruction["method"], details: empty.details })} className="mt-1 min-h-11 w-full border p-2">{["BANK_TRANSFER", "MOBILE_MONEY_AIRTEL", "MOBILE_MONEY_MTN", "CASH", "CHEQUE"].map(m => <option key={m} value={m}>{m.replace(/_/g, " ")}</option>)}</select></label>{fields.map(([key, label]) => <label key={key} className="block text-sm">{label}<input maxLength={key === "instructions" ? 300 : 160} value={form.details[key]} onChange={e => setForm({ ...form, details: { ...form.details, [key]: e.target.value } })} className="mt-1 min-h-11 w-full border p-2" /></label>)}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })} />Available for new statements</label></fieldset><div className="flex gap-2"><button disabled={busy} className="min-h-11 bg-editorial-black px-4 text-sm text-white">{busy ? "Saving…" : "Save agency instructions"}</button><button type="button" disabled={busy} className="min-h-11 border px-4" onClick={() => setEditing(false)}>Cancel</button></div></form>}
  </section>;
}
