"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { generationSchema, prepareStatement, statementUrl } from "@/lib/statements/document";
import { PaymentInstructionsEditor, type PaymentInstruction } from "./payment-instructions-editor";
export type StatementLease = { id: string; tenantName: string; tenantPhone: string; tenantEmail?: string | null; leaseStartDate: string; openingBalanceVerifiedAt?: string | null; openingBalance?: string | number | null; openingBalanceMonth?: number | null; openingBalanceYear?: number | null; status?: string; terminatedAt?: string | null };
export function TenantStatementDialog({ lease, month, year, onClose }: { lease: StatementLease; month: number; year: number; onClose: () => void }) {
  const [recipient, setRecipient] = useState({ name: lease.tenantName, phone: lease.tenantPhone, email: lease.tenantEmail || "", address: "" });
  const [instructions, setInstructions] = useState<PaymentInstruction[]>([]), [selected, setSelected] = useState<string[]>([]), [canManage, setCanManage] = useState(false), [verified, setVerified] = useState(Boolean(lease.openingBalanceVerifiedAt)), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(""), [savedId, setSavedId] = useState(""), [notes, setNotes] = useState("");
  const [baseline, setBaseline] = useState({ amount: String(lease.openingBalance ?? ""), month: lease.openingBalanceMonth || new Date(lease.leaseStartDate).getUTCMonth() + 1, year: lease.openingBalanceYear || new Date(lease.leaseStartDate).getUTCFullYear(), reason: "", terminatedAt: lease.terminatedAt?.slice(0, 10) || "" });
  const [nonce, setNonce] = useState(0);
  const request = useRef({ signature: "", key: "" });
  useEffect(() => { let active = true; setLoading(true); void fetch("/api/statement-payment-instructions", { cache: "no-store" }).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to load payment instructions."); if (active) { setInstructions(d.instructions); setCanManage(d.canManage); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [nonce]);
  const verify = async (e: React.FormEvent) => {
    e.preventDefault(); if (!baseline.amount.trim() || !Number.isFinite(Number(baseline.amount)) || baseline.reason.trim().length < 10) { setError("Enter the verified opening balance and a reason of at least 10 characters."); return; }
    setBusy(true); setError(""); try { const r = await fetch(`/api/leases/${lease.id}/opening-balance`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...baseline, amount: Number(baseline.amount), terminatedAt: baseline.terminatedAt ? new Date(`${baseline.terminatedAt}T00:00:00+02:00`).toISOString() : undefined }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to verify opening balance."); setVerified(true); setSavedId(""); } catch(e) { setError(e instanceof Error ? e.message : "Unable to verify balance."); } finally { setBusy(false); }
  };
  const generate = async (e: React.FormEvent) => {
    e.preventDefault(); const signature = JSON.stringify({ leaseId: lease.id, month, year, recipient, paymentInstructionIds: selected, notes }); if (signature !== request.current.signature || savedId) request.current = { signature, key: crypto.randomUUID() }; setSavedId(""); setError(""); const parsed = generationSchema.safeParse({ kind: "TENANT", leaseId: lease.id, month, year, recipient, paymentInstructionIds: selected, notes, idempotencyKey: request.current.key });
    if (!parsed.success) { setError(parsed.error.issues.map(i => `${i.path.join(" ")}: ${i.message}`).join(" · ")); return; }
    setBusy(true); try { setSavedId(await prepareStatement(parsed.data)); } catch(e) { setError(e instanceof Error ? e.message : "Unable to prepare statement."); } finally { setBusy(false); }
  };
  return <Dialog open layer={90} onOpenChange={open => { if (!open && !busy) onClose(); }}><DialogContent className="max-h-[90dvh] w-[calc(100%-2rem)] max-w-xl overflow-y-auto p-5"><DialogHeader><DialogTitle>Prepare tenant statement</DialogTitle><DialogDescription>{month}/{year} · Recipient edits apply only to this statement.</DialogDescription></DialogHeader>{error && <p role="alert" className="border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    {!verified && <p className="border border-amber-200 bg-amber-50 p-3 text-sm">Management or finance must verify an opening balance before this statement can be generated.</p>}
    {canManage && <details className="border p-3" open={!verified}><summary className="cursor-pointer text-sm font-semibold">Verify opening balance</summary><form onSubmit={verify} className="mt-3 space-y-3"><p className="text-xs">Balance immediately before the effective billing month, including historical arrears or credits.</p><label className="block text-sm">Opening balance<input required type="number" step="0.01" value={baseline.amount} onChange={e => setBaseline({ ...baseline, amount: e.target.value })} className="mt-1 min-h-11 w-full border p-2" /></label><div className="grid grid-cols-2 gap-2"><label className="text-sm">Effective month<input required type="number" min={1} max={12} value={baseline.month} onChange={e => setBaseline({ ...baseline, month: Number(e.target.value) })} className="mt-1 min-h-11 w-full border p-2" /></label><label className="text-sm">Effective year<input required type="number" min={2020} max={2100} value={baseline.year} onChange={e => setBaseline({ ...baseline, year: Number(e.target.value) })} className="mt-1 min-h-11 w-full border p-2" /></label></div>{lease.status === "TERMINATED" && <label className="block text-sm">Effective termination date<input type="date" value={baseline.terminatedAt} onChange={e => setBaseline({ ...baseline, terminatedAt: e.target.value })} className="mt-1 min-h-11 w-full border p-2" /></label>}<label className="block text-sm">Verification reason<input required minLength={10} maxLength={500} value={baseline.reason} onChange={e => setBaseline({ ...baseline, reason: e.target.value })} className="mt-1 min-h-11 w-full border p-2" /></label><button disabled={busy} className="min-h-11 bg-editorial-black px-4 text-sm text-white">Save verified opening balance</button></form></details>}
    <form onSubmit={generate} className="space-y-3"><fieldset disabled={busy} className="space-y-3">{(["name", "phone", "email", "address"] as const).map(key => <label key={key} className="block text-sm">{key === "name" ? "Tenant / recipient name" : key === "address" ? "Recipient address" : key === "email" ? "Recipient email" : "Recipient phone"}<input required={key === "name"} type={key === "email" ? "email" : "text"} maxLength={key === "address" ? 300 : key === "phone" ? 40 : 160} value={recipient[key]} onChange={e => { setRecipient({ ...recipient, [key]: e.target.value }); setSavedId(""); }} className="mt-1 min-h-11 w-full border p-2" /></label>)}<fieldset className="space-y-2"><legend className="mb-2 text-sm font-semibold">Payment methods</legend>{loading ? <p className="text-sm" role="status">Loading agency payment instructions…</p> : instructions.filter(i => i.active).length ? instructions.filter(i => i.active).map(i => <label key={i.id} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(i.id)} onChange={e => { setSelected(v => e.target.checked ? [...v, i.id] : v.filter(id => id !== i.id)); setSavedId(""); }} />{i.label} · {i.method.replace(/_/g, " ")}</label>) : <p className="text-sm">No agency payment instructions are configured.</p>}</fieldset><label className="block text-sm">Statement notes (optional)<textarea maxLength={500} value={notes} onChange={e => { setNotes(e.target.value); setSavedId(""); }} className="mt-1 w-full border p-2" /></label></fieldset><button disabled={busy || loading || !verified || !selected.length} className="min-h-11 bg-editorial-black px-4 text-sm text-white disabled:opacity-50">{busy ? "Preparing statement…" : "Generate tenant statement"}</button></form>
    {savedId && <div role="status" className="border border-emerald-200 bg-emerald-50 p-3"><p className="mb-2 text-sm">Your saved tenant statement is ready.</p><Link target="_blank" rel="noopener noreferrer" href={statementUrl(savedId)} className="inline-flex min-h-11 items-center bg-[#16382B] px-4 text-sm text-white">Open tenant statement viewer</Link></div>}
    {canManage && <PaymentInstructionsEditor instructions={instructions} onSaved={() => { setNonce(v => v + 1); setSavedId(""); }} />}
  </DialogContent></Dialog>;
}
